import type { CenterHospital, CenterDoctor, CenterService } from './types';

const now = '2025-07-30T00:00:00.000Z';

export const INITIAL_CENTER_HOSPITALS: CenterHospital[] = [
  // SHANGHAI
  {
    id: "hosp-sh-fudan-tumor",
    name: "复旦大学附属肿瘤医院",
    shortName: "复旦肿瘤",
    city: "上海",
    province: "上海",
    country: "中国",
    latitude: 31.19,
    longitude: 121.455,
    hospitalLevel: "3A",
    hospitalType: "cancer_center",
    pancreaticAnnualSurgeries: 800,
    hasMDT: true,
    mdtSchedule: "周三下午多学科 MDT 联合门诊",
    contact: "sh_ca_hospital",
    sourceUrls: ["https://www.shca.org.cn/"],
    dataQuality: "public",
    qualityScore: 95,
    updatedAt: now,
  },
  {
    id: "hosp-sh-ruijin",
    name: "上海交通大学医学院附属瑞金医院",
    shortName: "瑞金医院",
    city: "上海",
    province: "上海",
    country: "中国",
    latitude: 31.215,
    longitude: 121.468,
    hospitalLevel: "3A",
    hospitalType: "general",
    pancreaticAnnualSurgeries: 500,
    hasMDT: true,
    contact: "sh-ruijin",
    sourceUrls: ["http://www.rjh.com.cn/"],
    dataQuality: "public",
    qualityScore: 92,
    updatedAt: now,
  },
  {
    id: "hosp-sh-changhai",
    name: "海军军医大学第一附属医院 (上海长海医院)",
    shortName: "长海医院",
    city: "上海",
    province: "上海",
    country: "中国",
    latitude: 31.30,
    longitude: 121.52,
    hospitalLevel: "3A",
    hospitalType: "general",
    pancreaticAnnualSurgeries: 450,
    hasMDT: true,
    contact: "chhospital",
    sourceUrls: ["http://www.chhospital.com.cn/"],
    dataQuality: "public",
    qualityScore: 90,
    updatedAt: now,
  },
  {
    id: "hosp-sh-zhongshan",
    name: "复旦大学附属中山医院",
    shortName: "中山医院",
    city: "上海",
    province: "上海",
    country: "中国",
    latitude: 31.20,
    longitude: 121.454,
    hospitalLevel: "3A",
    hospitalType: "general",
    hasMDT: true,
    contact: "gh_731e8b26f5ff",
    sourceUrls: ["https://www.zs-hospital.sh.cn/"],
    dataQuality: "public",
    qualityScore: 88,
    updatedAt: now,
  },
  {
    id: "hosp-sh-huashan",
    name: "复旦大学附属华山医院",
    shortName: "华山医院",
    city: "上海",
    province: "上海",
    country: "中国",
    latitude: 31.22,
    longitude: 121.436,
    hospitalLevel: "3A",
    hospitalType: "general",
    hasMDT: true,
    contact: "hs_fudan",
    sourceUrls: ["https://www.huashan.org.cn/"],
    dataQuality: "public",
    qualityScore: 87,
    updatedAt: now,
  },
  {
    id: "hosp-sh-shi-yi",
    name: "上海市第一人民医院",
    shortName: "市一医院",
    city: "上海",
    province: "上海",
    country: "中国",
    latitude: 31.245,
    longitude: 121.485,
    hospitalLevel: "3A",
    hospitalType: "general",
    hasMDT: true,
    contact: "sh_first_hosp",
    sourceUrls: ["https://www.firsthospital.cn/"],
    dataQuality: "public",
    qualityScore: 82,
    updatedAt: now,
  },

  // BEIJING
  {
    id: "hosp-bj-xiehe",
    name: "北京协和医院",
    shortName: "协和医院",
    city: "北京",
    province: "北京",
    country: "中国",
    latitude: 39.91,
    longitude: 116.41,
    hospitalLevel: "3A",
    hospitalType: "general",
    accreditedBy: ["JCI"],
    pancreaticAnnualSurgeries: 600,
    hasMDT: true,
    mdtSchedule: "周三 MDT 绿道（协和 App 预约）",
    contact: "pumch_hospital",
    sourceUrls: ["https://www.pumch.cn/"],
    dataQuality: "public",
    qualityScore: 96,
    updatedAt: now,
  },
  {
    id: "hosp-bj-beida-tumor",
    name: "北京大学肿瘤医院",
    shortName: "北大肿瘤",
    city: "北京",
    province: "北京",
    country: "中国",
    latitude: 39.92,
    longitude: 116.32,
    hospitalLevel: "3A",
    hospitalType: "cancer_center",
    hasMDT: true,
    contact: "bj-pku-tumor",
    sourceUrls: ["https://www.bjcancer.org/"],
    dataQuality: "public",
    qualityScore: 90,
    updatedAt: now,
  },
  {
    id: "hosp-bj-301",
    name: "中国人民解放军总医院 (301医院)",
    shortName: "301医院",
    city: "北京",
    province: "北京",
    country: "中国",
    latitude: 39.90,
    longitude: 116.27,
    hospitalLevel: "3A",
    hospitalType: "general",
    hasMDT: true,
    contact: "301_hospital",
    sourceUrls: ["http://www.301hospital.com.cn/"],
    dataQuality: "public",
    qualityScore: 86,
    updatedAt: now,
  },

  // JIANGSU
  {
    id: "hosp-js-shengrenmin",
    name: "江苏省人民医院",
    shortName: "江苏省人民医院",
    city: "南京",
    province: "江苏",
    country: "中国",
    latitude: 32.05,
    longitude: 118.77,
    hospitalLevel: "3A",
    hospitalType: "general",
    pancreaticAnnualSurgeries: 400,
    hasMDT: true,
    contact: "jsph-panc",
    sourceUrls: ["http://www.jsph.net/"],
    dataQuality: "public",
    qualityScore: 88,
    updatedAt: now,
  },
  {
    id: "hosp-js-gulou",
    name: "南京大学医学院附属鼓楼医院",
    shortName: "鼓楼医院",
    city: "南京",
    province: "江苏",
    country: "中国",
    latitude: 32.06,
    longitude: 118.78,
    hospitalLevel: "3A",
    hospitalType: "general",
    hasMDT: true,
    contact: "njglyy1892",
    sourceUrls: ["http://www.njglyy.com/"],
    dataQuality: "public",
    qualityScore: 85,
    updatedAt: now,
  },
  {
    id: "hosp-js-sudayifu",
    name: "苏州大学附属第一医院",
    shortName: "苏大附一院",
    city: "苏州",
    province: "江苏",
    country: "中国",
    latitude: 31.32,
    longitude: 120.63,
    hospitalLevel: "3A",
    hospitalType: "general",
    hasMDT: true,
    contact: "sdafy_hosp",
    sourceUrls: ["http://fyy.sdfyy.cn/"],
    dataQuality: "public",
    qualityScore: 82,
    updatedAt: now,
  },

  // SICHUAN
  {
    id: "hosp-sc-huaxi",
    name: "四川大学华西医院",
    shortName: "华西医院",
    city: "成都",
    province: "四川",
    country: "中国",
    latitude: 30.64,
    longitude: 104.06,
    hospitalLevel: "3A",
    hospitalType: "general",
    pancreaticAnnualSurgeries: 500,
    hasMDT: true,
    contact: "WestChina_Hospital",
    sourceUrls: ["http://www.wchscu.cn/"],
    dataQuality: "public",
    qualityScore: 93,
    updatedAt: now,
  },
  {
    id: "hosp-sc-renmin",
    name: "四川省人民医院",
    shortName: "四川省人民医院",
    city: "成都",
    province: "四川",
    country: "中国",
    latitude: 30.66,
    longitude: 104.03,
    hospitalLevel: "3A",
    hospitalType: "general",
    hasMDT: true,
    contact: "gh_sichuan_prov_hosp",
    sourceUrls: ["http://www.samsph.com/"],
    dataQuality: "public",
    qualityScore: 80,
    updatedAt: now,
  },

  // ZHEJIANG
  {
    id: "hosp-zj-zhedaer",
    name: "浙江大学医学院附属第二医院",
    shortName: "浙大二院",
    city: "杭州",
    province: "浙江",
    country: "中国",
    latitude: 30.25,
    longitude: 120.17,
    hospitalLevel: "3A",
    hospitalType: "general",
    hasMDT: true,
    mdtSchedule: "周四下午胰特会诊诊室",
    contact: "z2hospital",
    sourceUrls: ["http://www.z2hospital.com/"],
    dataQuality: "public",
    qualityScore: 88,
    updatedAt: now,
  },
  {
    id: "hosp-zj-zhedayi",
    name: "浙江大学医学院附属第一医院",
    shortName: "浙大一院",
    city: "杭州",
    province: "浙江",
    country: "中国",
    latitude: 30.26,
    longitude: 120.18,
    hospitalLevel: "3A",
    hospitalType: "general",
    hasMDT: true,
    contact: "zdyy1947",
    sourceUrls: ["http://www.zy91.com/"],
    dataQuality: "public",
    qualityScore: 86,
    updatedAt: now,
  },
  {
    id: "hosp-zj-shaoyifu",
    name: "浙江大学医学院附属邵逸夫医院",
    shortName: "邵逸夫医院",
    city: "杭州",
    province: "浙江",
    country: "中国",
    latitude: 30.25,
    longitude: 120.20,
    hospitalLevel: "3A",
    hospitalType: "general",
    hasMDT: true,
    contact: "srrsh1994",
    sourceUrls: ["http://www.srrsh.com/"],
    dataQuality: "public",
    qualityScore: 83,
    updatedAt: now,
  },

  // FUJIAN
  {
    id: "hosp-fj-yifuyuan",
    name: "福建医科大学附属第一医院",
    shortName: "福医附一",
    city: "福州",
    province: "福建",
    country: "中国",
    latitude: 26.06,
    longitude: 119.30,
    hospitalLevel: "3A",
    hospitalType: "general",
    hasMDT: true,
    contact: "fyfy1860",
    sourceUrls: ["http://www.fyyy.com/"],
    dataQuality: "public",
    qualityScore: 80,
    updatedAt: now,
  },
  {
    id: "hosp-fj-xiehe",
    name: "福建医科大学附属协和医院",
    shortName: "福医协和",
    city: "福州",
    province: "福建",
    country: "中国",
    latitude: 26.08,
    longitude: 119.30,
    hospitalLevel: "3A",
    hospitalType: "general",
    hasMDT: true,
    contact: "fjsfxyy",
    sourceUrls: ["http://www.fjxiehe.com/"],
    dataQuality: "public",
    qualityScore: 78,
    updatedAt: now,
  },

  // HEBEI
  {
    id: "hosp-hb-hebdaer",
    name: "河北医科大学第二医院",
    shortName: "河北医大二院",
    city: "石家庄",
    province: "河北",
    country: "中国",
    latitude: 38.05,
    longitude: 114.48,
    hospitalLevel: "3A",
    hospitalType: "general",
    hasMDT: true,
    contact: "hb2h_sjz",
    sourceUrls: ["http://www.hb2h.com/"],
    dataQuality: "public",
    qualityScore: 78,
    updatedAt: now,
  },
  {
    id: "hosp-hb-hebdafr",
    name: "河北医科大学第四医院 (河北省肿瘤医院)",
    shortName: "河北肿瘤医院",
    city: "石家庄",
    province: "河北",
    country: "中国",
    latitude: 38.04,
    longitude: 114.52,
    hospitalLevel: "3A",
    hospitalType: "cancer_center",
    hasMDT: true,
    sourceUrls: ["http://www.hbydsy.com/"],
    dataQuality: "public",
    qualityScore: 76,
    updatedAt: now,
  },

  // INTERNATIONAL
  {
    id: "hosp-de-heidelberg",
    name: "德国海德堡大学附属医院",
    shortName: "海德堡胰腺中心",
    city: "海德堡",
    province: "巴登-符腾堡",
    country: "德国",
    latitude: 49.4122,
    longitude: 8.6724,
    hospitalLevel: "international",
    hospitalType: "university",
    accreditedBy: ["JCI"],
    pancreaticAnnualSurgeries: 900,
    hasMDT: true,
    contact: "heinz.pancreas@med.uni-heidelberg.de",
    website: "https://www.klinikum.uni-heidelberg.de/",
    sourceUrls: ["https://www.klinikum.uni-heidelberg.de/"],
    dataQuality: "public",
    qualityScore: 98,
    updatedAt: now,
  },
  {
    id: "hosp-us-mdanderson",
    name: "MD安德森癌症中心",
    shortName: "MD Anderson",
    city: "休斯顿",
    province: "德克萨斯州",
    country: "美国",
    latitude: 29.7072,
    longitude: -95.3963,
    hospitalLevel: "international",
    hospitalType: "cancer_center",
    accreditedBy: ["JCI"],
    pancreaticAnnualSurgeries: 600,
    hasMDT: true,
    contact: "pancreaticcenter@mdanderson.org",
    website: "https://www.mdanderson.org/",
    sourceUrls: ["https://www.mdanderson.org/"],
    dataQuality: "public",
    qualityScore: 97,
    updatedAt: now,
  },
  {
    id: "hosp-jp-kyoto",
    name: "京都大学附属医院",
    shortName: "京都大学医院",
    city: "京都",
    province: "京都府",
    country: "日本",
    latitude: 35.0210,
    longitude: 135.7792,
    hospitalLevel: "international",
    hospitalType: "university",
    pancreaticAnnualSurgeries: 350,
    hasMDT: true,
    contact: "kyoto-pancreas-hosp@kuhp.kyoto-u.ac.jp",
    website: "https://www.kuhp.kyoto-u.ac.jp/",
    sourceUrls: ["https://www.kuhp.kyoto-u.ac.jp/"],
    dataQuality: "public",
    qualityScore: 94,
    updatedAt: now,
  },
];

export const INITIAL_CENTER_DOCTORS: CenterDoctor[] = [
  // SHANGHAI
  {
    id: "doc-sh-yuxianjun",
    name: "虞先濬",
    title: "教授/主任医师",
    hospitalIds: ["hosp-sh-fudan-tumor"],
    departmentName: "胰腺外科",
    specialties: ["胰腺癌新辅助化疗", "胰十二指肠切除术", "精准靶向治疗(NP)", "多学科MDT"],
    academicTitle: "博导",
    academicOrg: "复旦大学附属肿瘤医院副院长",
    sourceUrls: ["https://www.shca.org.cn/"],
    dataQuality: "public",
    qualityScore: 95,
    updatedAt: now,
  },
  {
    id: "doc-sh-pengchenghong",
    name: "彭承宏",
    title: "教授/主任医师",
    hospitalIds: ["hosp-sh-ruijin"],
    departmentName: "普外科",
    specialties: ["达芬奇机器人微创胰腺切除", "血管重建"],
    academicTitle: "博导",
    sourceUrls: ["http://www.rjh.com.cn/"],
    dataQuality: "public",
    qualityScore: 92,
    updatedAt: now,
  },
  {
    id: "doc-sh-shenbaiyong",
    name: "沈柏用",
    title: "教授/主任医师",
    hospitalIds: ["hosp-sh-ruijin"],
    departmentName: "普外科",
    specialties: ["胰腺癌综合治疗", "微创手术", "达芬奇机器人手术"],
    academicTitle: "博导",
    sourceUrls: ["http://www.rjh.com.cn/"],
    dataQuality: "public",
    qualityScore: 90,
    updatedAt: now,
  },
  {
    id: "doc-sh-jingang",
    name: "金钢",
    title: "教授/主任医师",
    hospitalIds: ["hosp-sh-changhai"],
    departmentName: "肝胆胰外科",
    specialties: ["EUS-FNA穿刺诊断", "消化大出血急诊栓塞", "重症胰腺炎管理", "胰瘘治疗"],
    academicTitle: "博导",
    sourceUrls: ["http://www.chhospital.com.cn/"],
    dataQuality: "public",
    qualityScore: 90,
    updatedAt: now,
  },
  {
    id: "doc-sh-liuliang",
    name: "刘亮",
    title: "教授/主任医师",
    hospitalIds: ["hosp-sh-zhongshan"],
    departmentName: "胰腺外科",
    specialties: ["胰腺癌综合治疗", "射频消融(RFA)", "血管介入栓塞(TAE)"],
    academicTitle: "博导",
    sourceUrls: ["https://www.zs-hospital.sh.cn/"],
    dataQuality: "public",
    qualityScore: 86,
    updatedAt: now,
  },
  {
    id: "doc-sh-wangwenquan",
    name: "王文权",
    title: "教授/主任医师",
    hospitalIds: ["hosp-sh-zhongshan"],
    departmentName: "胰腺外科",
    specialties: ["胰腺内分泌肿瘤(NETs)", "多药MDT"],
    sourceUrls: ["https://www.zs-hospital.sh.cn/"],
    dataQuality: "public",
    qualityScore: 82,
    updatedAt: now,
  },
  {
    id: "doc-sh-fudeliang",
    name: "傅德良",
    title: "教授/主任医师",
    hospitalIds: ["hosp-sh-huashan"],
    departmentName: "胰腺外科",
    specialties: ["血管剥离及精细缝合", "后腹膜侵犯清扫", "局部冷热消融", "腹腔神经丛阻滞(CPB)"],
    academicTitle: "博导",
    sourceUrls: ["https://www.huashan.org.cn/"],
    dataQuality: "public",
    qualityScore: 88,
    updatedAt: now,
  },
  {
    id: "doc-sh-longjiang",
    name: "龙江",
    title: "教授/主任医师",
    hospitalIds: ["hosp-sh-shi-yi"],
    departmentName: "胰腺外科",
    specialties: ["PEI精细管理", "多模态消融", "数字化病程随访"],
    sourceUrls: ["https://www.firsthospital.cn/"],
    dataQuality: "public",
    qualityScore: 82,
    updatedAt: now,
  },

  // BEIJING
  {
    id: "doc-bj-zhaoyupei",
    name: "赵玉沛",
    title: "教授/主任医师",
    hospitalIds: ["hosp-bj-xiehe"],
    departmentName: "基本外科",
    specialties: ["胰腺癌综合诊治", "胰岛素瘤诊治", "疑难罕见疾病MDT"],
    academicTitle: "院士",
    academicOrg: "中国工程院院士，国际胰腺学会前主席",
    sourceUrls: ["https://www.pumch.cn/"],
    dataQuality: "public",
    qualityScore: 98,
    updatedAt: now,
  },
  {
    id: "doc-bj-zhangtaiping",
    name: "张太平",
    title: "教授/主任医师",
    hospitalIds: ["hosp-bj-xiehe"],
    departmentName: "基本外科",
    specialties: ["胰腺癌诊治", "机器人胰腺癌根治术"],
    academicTitle: "博导",
    academicOrg: "基本外科教研室主任",
    sourceUrls: ["https://www.pumch.cn/"],
    dataQuality: "public",
    qualityScore: 92,
    updatedAt: now,
  },
  {
    id: "doc-bj-haochunyi",
    name: "郝纯毅",
    title: "教授/主任医师",
    hospitalIds: ["hosp-bj-beida-tumor"],
    departmentName: "肝胆胰外二科",
    specialties: ["胰腺肿瘤综合治疗", "化疗转化方案", "多线化疗耐药分析"],
    academicTitle: "博导",
    academicOrg: "CSCO胰腺癌专委会前任主任委员",
    sourceUrls: ["https://www.bjcancer.org/"],
    dataQuality: "public",
    qualityScore: 92,
    updatedAt: now,
  },
  {
    id: "doc-bj-xingbaocai",
    name: "邢宝才",
    title: "教授/主任医师",
    hospitalIds: ["hosp-bj-beida-tumor"],
    departmentName: "肝胆胰外一科",
    specialties: ["胰腺癌综合治疗", "消化道肿瘤"],
    sourceUrls: ["https://www.bjcancer.org/"],
    dataQuality: "public",
    qualityScore: 88,
    updatedAt: now,
  },
  {
    id: "doc-bj-lushichun",
    name: "卢实春",
    title: "教授/主任医师",
    hospitalIds: ["hosp-bj-301"],
    departmentName: "肝胆胰外科学部",
    specialties: ["重症外科抢救", "复杂血管重建修复"],
    sourceUrls: ["http://www.301hospital.com.cn/"],
    dataQuality: "public",
    qualityScore: 85,
    updatedAt: now,
  },

  // JIANGSU
  {
    id: "doc-js-jiangkui",
    name: "蒋奎荣",
    title: "教授/主任医师",
    hospitalIds: ["hosp-js-shengrenmin"],
    departmentName: "普外科",
    specialties: ["胰腺癌外科治疗", "完全腔镜胰吻合"],
    sourceUrls: ["http://www.jsph.net/"],
    dataQuality: "public",
    qualityScore: 88,
    updatedAt: now,
  },
  {
    id: "doc-js-qianzhuyin",
    name: "钱祝银",
    title: "教授/主任医师",
    hospitalIds: ["hosp-js-shengrenmin"],
    departmentName: "肝胆胰外科",
    specialties: ["冷冻消融", "胰腺癌微创治疗", "消融复合内引"],
    sourceUrls: ["http://www.jsph.net/"],
    dataQuality: "public",
    qualityScore: 86,
    updatedAt: now,
  },
  {
    id: "doc-js-miaoyi",
    name: "苗毅",
    title: "教授/终身学术带头人",
    hospitalIds: ["hosp-js-shengrenmin"],
    departmentName: "胰腺中心",
    specialties: ["胰腺外科", "苗氏胰改道重建"],
    academicTitle: "博导",
    sourceUrls: ["http://www.jsph.net/"],
    dataQuality: "public",
    qualityScore: 92,
    updatedAt: now,
  },

  // SICHUAN
  {
    id: "doc-sc-pengbing",
    name: "彭兵",
    title: "教授/主任医师",
    hospitalIds: ["hosp-sc-huaxi"],
    departmentName: "胰腺外科",
    specialties: ["腹腔镜胰十二指肠切除(LPD)", "达芬奇机器人微创", "复杂血管改道切除"],
    academicTitle: "博导",
    sourceUrls: ["http://www.wchscu.cn/"],
    dataQuality: "public",
    qualityScore: 93,
    updatedAt: now,
  },
  {
    id: "doc-sc-liuxubao",
    name: "刘续宝",
    title: "教授/主任医师",
    hospitalIds: ["hosp-sc-huaxi"],
    departmentName: "胰腺外科",
    specialties: ["胰腺癌综合治疗", "复杂胰腺切除"],
    sourceUrls: ["http://www.wchscu.cn/"],
    dataQuality: "public",
    qualityScore: 88,
    updatedAt: now,
  },

  // ZHEJIANG
  {
    id: "doc-zj-baixueli",
    name: "白雪莉",
    title: "教授/主任医师",
    hospitalIds: ["hosp-zj-zhedaer"],
    departmentName: "肝胆胰外科",
    specialties: ["血管剥离切除", "淋巴清扫", "原位血管移植重建"],
    academicTitle: "博导",
    sourceUrls: ["http://www.z2hospital.com/"],
    dataQuality: "public",
    qualityScore: 90,
    updatedAt: now,
  },
  {
    id: "doc-zj-liangtingbo",
    name: "梁廷波",
    title: "教授/主任医师",
    hospitalIds: ["hosp-zj-zhedayi"],
    departmentName: "普外科",
    specialties: ["重症器官移植", "复杂术后感染控制", "FMT肠菌移植化疗减毒"],
    academicTitle: "博导",
    sourceUrls: ["http://www.zy91.com/"],
    dataQuality: "public",
    qualityScore: 88,
    updatedAt: now,
  },
  {
    id: "doc-zj-yuhong",
    name: "虞洪",
    title: "教授/主任医师",
    hospitalIds: ["hosp-zj-shaoyifu"],
    departmentName: "微创胰腺中心",
    specialties: ["完全腔镜微创切除", "保脾保幽门保留术"],
    sourceUrls: ["http://www.srrsh.com/"],
    dataQuality: "public",
    qualityScore: 84,
    updatedAt: now,
  },

  // INTERNATIONAL
  {
    id: "doc-de-buchler",
    name: "Prof. Markus W. Büchler",
    title: "教授/荣誉主任",
    hospitalIds: ["hosp-de-heidelberg"],
    departmentName: "胰腺外科",
    specialties: ["Whipple精密外科手术", "复杂胰腺癌MDT"],
    academicTitle: "博导/世界级学术带头人",
    sourceUrls: ["https://www.klinikum.uni-heidelberg.de/"],
    dataQuality: "public",
    qualityScore: 98,
    updatedAt: now,
  },
  {
    id: "doc-us-maitra",
    name: "Dr. Anirban Maitra",
    title: "教授/研究员",
    hospitalIds: ["hosp-us-mdanderson"],
    departmentName: "胰腺癌研究",
    specialties: ["胰腺癌分子靶向", "ATM/ATR/BRCA合成致死", "新型KRAS靶点"],
    academicTitle: "胰腺癌研究巨擘",
    sourceUrls: ["https://www.mdanderson.org/"],
    dataQuality: "public",
    qualityScore: 96,
    updatedAt: now,
  },
  {
    id: "doc-jp-hatano",
    name: "Prof. Etsuro Hatano",
    title: "教授/主任医师",
    hospitalIds: ["hosp-jp-kyoto"],
    departmentName: "肝胆胰微创外科",
    specialties: ["达芬奇机器人辅助微创切除", "保脾保幽门保留微创"],
    sourceUrls: ["https://www.kuhp.kyoto-u.ac.jp/"],
    dataQuality: "public",
    qualityScore: 92,
    updatedAt: now,
  },
];

export const INITIAL_CENTER_SERVICES: CenterService[] = [
  // Fudan Tumor services
  {
    id: "svc-sh-fudan-mdt",
    name: "胰腺癌多学科联合会诊(MDT)",
    description: "周三下午多学科MDT联合门诊，虞先濬教授团队领衔，涵盖外科、肿瘤内科、放疗科、病理科、影像科",
    category: "surgery",
    hospitalId: "hosp-sh-fudan-tumor",
    departmentName: "胰腺外科",
    availability: "within_week",
    insuranceCoverage: ["上海医保"],
    sourceUrls: ["https://www.shca.org.cn/"],
    dataQuality: "public",
    qualityScore: 90,
    updatedAt: now,
  },
  {
    id: "svc-sh-fudan-targeted",
    name: "精准靶向与免疫治疗",
    description: "基于高通量基因测序的CLDN18.2抗体、KRAS G12D靶点等个性化靶向治疗和免疫联合方案",
    category: "clinical_trial",
    hospitalId: "hosp-sh-fudan-tumor",
    departmentName: "肿瘤内科",
    availability: "within_month",
    sourceUrls: ["https://www.shca.org.cn/"],
    dataQuality: "public",
    qualityScore: 88,
    updatedAt: now,
  },

  // Ruijin services
  {
    id: "svc-sh-ruijin-robot",
    name: "达芬奇机器人微创胰十二指肠切除术",
    description: "彭承宏/沈柏用教授团队，机器人微创胰腺切除比例高，ERAS规范健全",
    category: "surgery",
    hospitalId: "hosp-sh-ruijin",
    departmentName: "普外科",
    availability: "within_month",
    insuranceCoverage: ["上海医保"],
    sourceUrls: ["http://www.rjh.com.cn/"],
    dataQuality: "public",
    qualityScore: 88,
    updatedAt: now,
  },
  {
    id: "svc-sh-ruijin-nutrition",
    name: "临床营养支持",
    description: "针对晚期恶病质、术后消化酶不全或吸收障碍，提供口服短肽与肠友代乳专门指导",
    category: "nutrition",
    hospitalId: "hosp-sh-ruijin",
    departmentName: "临床营养科",
    availability: "within_week",
    insuranceCoverage: ["上海医保"],
    sourceUrls: ["http://www.rjh.com.cn/"],
    dataQuality: "public",
    qualityScore: 85,
    updatedAt: now,
  },

  // Changhai services
  {
    id: "svc-sh-changhai-eus",
    name: "超声内镜微创穿刺诊断(EUS-FNA)",
    description: "金钢主任团队，超声内镜下微创穿刺诊断技术全国顶尖，诊断准确率极高",
    category: "intervention",
    hospitalId: "hosp-sh-changhai",
    departmentName: "消化内科",
    availability: "within_week",
    insuranceCoverage: ["上海医保"],
    sourceUrls: ["http://www.chhospital.com.cn/"],
    dataQuality: "public",
    qualityScore: 90,
    updatedAt: now,
  },
  {
    id: "svc-sh-changhai-panc-inflammation",
    name: "难治性胰腺炎管理",
    description: "针对重症慢性胰腺炎、难治性残端胰瘘的无创负压冲洗及多学科胰旁引流管管理",
    category: "intervention",
    hospitalId: "hosp-sh-changhai",
    departmentName: "肝胆胰外科",
    availability: "within_week",
    insuranceCoverage: ["上海医保"],
    sourceUrls: ["http://www.chhospital.com.cn/"],
    dataQuality: "public",
    qualityScore: 85,
    updatedAt: now,
  },

  // Zhongshan services
  {
    id: "svc-sh-zhongshan-intervention",
    name: "介入止血与减黄急救",
    description: "刘亮/王文权教授团队，血管造影栓塞(TAE)止血、肠梗阻消化道支架、内镜胆道PTCD减黄",
    category: "intervention",
    hospitalId: "hosp-sh-zhongshan",
    departmentName: "胰腺外科/介入科",
    availability: "immediate",
    insuranceCoverage: ["上海医保"],
    sourceUrls: ["https://www.zs-hospital.sh.cn/"],
    dataQuality: "public",
    qualityScore: 86,
    updatedAt: now,
  },

  // Huashan services
  {
    id: "svc-sh-huashan-cpb",
    name: "超声引导腹腔神经丛阻滞(CPB)",
    description: "傅德良教授团队，针对腹膜后神经丛侵犯剧痛的精准镇痛介入",
    category: "palliative",
    hospitalId: "hosp-sh-huashan",
    departmentName: "疼痛科",
    availability: "within_week",
    insuranceCoverage: ["上海医保"],
    sourceUrls: ["https://www.huashan.org.cn/"],
    dataQuality: "public",
    qualityScore: 84,
    updatedAt: now,
  },

  // PUMCH services
  {
    id: "svc-bj-xiehe-insulinoma",
    name: "胰岛素瘤等神经内分泌肿瘤诊治",
    description: "赵玉沛院士团队，亚洲最大宗胰岛素瘤诊治中心（600余例），超声内镜精确定位",
    category: "surgery",
    hospitalId: "hosp-bj-xiehe",
    departmentName: "基本外科",
    availability: "within_month",
    insuranceCoverage: ["北京医保"],
    sourceUrls: ["https://www.pumch.cn/"],
    dataQuality: "public",
    qualityScore: 95,
    updatedAt: now,
  },
  {
    id: "svc-bj-xiehe-robot",
    name: "国产机器人胰腺癌根治术",
    description: "2024年完成首例国产机器人胰腺癌根治术，提供微创精准切除",
    category: "surgery",
    hospitalId: "hosp-bj-xiehe",
    departmentName: "基本外科",
    availability: "within_month",
    insuranceCoverage: ["北京医保"],
    sourceUrls: ["https://www.pumch.cn/"],
    dataQuality: "public",
    qualityScore: 92,
    updatedAt: now,
  },

  // Huaxi services
  {
    id: "svc-sc-huaxi-lpd",
    name: "腹腔镜胰十二指肠切除术(LPD)",
    description: "彭兵教授团队，西部首例3D-LPD，联合血管切除重建等高难度微创术式",
    category: "surgery",
    hospitalId: "hosp-sc-huaxi",
    departmentName: "胰腺外科",
    availability: "within_month",
    insuranceCoverage: ["四川医保", "跨省医保"],
    sourceUrls: ["http://www.wchscu.cn/"],
    dataQuality: "public",
    qualityScore: 92,
    updatedAt: now,
  },
  {
    id: "svc-sc-huaxi-nutrition",
    name: "临床营养特膳支持",
    description: "针对术后顽固吸收不全、体重骤缩、胃瘫，提供高热比分子级口服与肠内营养支持",
    category: "nutrition",
    hospitalId: "hosp-sc-huaxi",
    departmentName: "临床营养科",
    availability: "within_week",
    insuranceCoverage: ["四川医保"],
    sourceUrls: ["http://www.wchscu.cn/"],
    dataQuality: "public",
    qualityScore: 88,
    updatedAt: now,
  },

  // ZJU Second services
  {
    id: "svc-zj-zhedaer-mdt",
    name: "周四胰特会诊",
    description: "白雪莉/严盛教授团队，周四下午多学科胰特会诊诊区，集中解决复杂胰腺病例",
    category: "surgery",
    hospitalId: "hosp-zj-zhedaer",
    departmentName: "肝胆胰外科",
    availability: "within_week",
    insuranceCoverage: ["浙江医保"],
    sourceUrls: ["http://www.z2hospital.com/"],
    dataQuality: "public",
    qualityScore: 86,
    updatedAt: now,
  },

  // ZJU First services
  {
    id: "svc-zj-zhedayi-fmt",
    name: "肠道菌群移植(FMT)化疗减毒",
    description: "梁廷波教授团队，开创FMT肠菌移植降低化疗消化副反应的创新疗法",
    category: "clinical_trial",
    hospitalId: "hosp-zj-zhedayi",
    departmentName: "消化肿瘤内科",
    availability: "within_month",
    sourceUrls: ["http://www.zy91.com/"],
    dataQuality: "public",
    qualityScore: 85,
    updatedAt: now,
  },

  // International HD surgery
  {
    id: "svc-de-heidelberg-whipple",
    name: "Whipple精密外科手术",
    description: "全球胰腺癌手术和综合诊疗中枢，胰腺外科切除数量居世界前列",
    category: "surgery",
    hospitalId: "hosp-de-heidelberg",
    departmentName: "胰腺外科",
    availability: "within_month",
    sourceUrls: ["https://www.klinikum.uni-heidelberg.de/"],
    dataQuality: "public",
    qualityScore: 98,
    updatedAt: now,
  },

  // MD Anderson targeted therapy
  {
    id: "svc-us-mdanderson-targeted",
    name: "胰腺癌分子靶向治疗",
    description: "Anirban Maitra领衔，ATM/ATR/BRCA合成致死筛查，新型KRAS靶点联合免疫抗体",
    category: "clinical_trial",
    hospitalId: "hosp-us-mdanderson",
    departmentName: "胰腺癌研究",
    availability: "within_month",
    sourceUrls: ["https://www.mdanderson.org/"],
    dataQuality: "public",
    qualityScore: 96,
    updatedAt: now,
  },

  // Kyoto minimally invasive
  {
    id: "svc-jp-kyoto-robot",
    name: "达芬奇机器人辅助微创切除",
    description: "Prof. Etsuro Hatano团队，亚洲顶尖微创胰腺切除，极低中转开腹率",
    category: "surgery",
    hospitalId: "hosp-jp-kyoto",
    departmentName: "肝胆胰微创外科",
    availability: "within_month",
    sourceUrls: ["https://www.kuhp.kyoto-u.ac.jp/"],
    dataQuality: "public",
    qualityScore: 92,
    updatedAt: now,
  },
];
