import { OSINTItem, ResourceCenter, SystemReport15Day } from './types';

export const INITIAL_OSINT_FEED: OSINTItem[] = [
  {
    id: "osint-1",
    title: "FDA Grants Breakthrough Therapy Designation for MRTX1133 in KRAS G12D-Mutant Advanced Pancreatic Ductal Adenocarcinoma (PDAC)",
    url: "https://www.fda.gov/news-events/press-announcements",
    source: "FDA Newsroom",
    publishedAt: "2026-06-21T08:30:00Z",
    country: "USA",
    category: "drug",
    entities: ["MRTX1133", "KRAS G12D", "PDAC", "Breakthrough Therapy"],
    importanceScore: 9.8,
    summary: "美国FDA授予强效非共价KRAS G12D抑制剂MRTX1133突破性疗法认定。临床I期早期数据显示，在经治的KRAS G12D突变晚期胰腺癌患者中客观缓解率（ORR）达到31%，且安全性良好。这标志着直接针对胰腺癌最常见突变（KRAS G12D占比约40%）的靶向治疗取得重大突破。",
    evidenceLevel: "B",
    clickable: true
  },
  {
    id: "osint-2",
    title: "Phase III NAPOLI-3 Trial Confirms NALIRIFOX (Liposomal Irinotecan + 5-FU/LV + Oxaliplatin) Over Gem+Nab-Paclitaxel as First-Line Treatment for Metastatic PDAC",
    url: "https://www.thelancet.com/journals/lanonc",
    source: "The Lancet Oncology",
    publishedAt: "2026-06-20T14:15:00Z",
    country: "Global",
    category: "trial",
    entities: ["NALIRIFOX", "Metastatic PDAC", "ASCO GI", "First-Line Chemotherapy"],
    importanceScore: 9.2,
    summary: "发表于《柳叶刀·肿瘤学》的NAPOLI-3随机III期临床试验结果确认：相比于传统的吉西他滨联合白蛋白Paclitaxel（Gem+Nab-P），采用NALIRIFOX方案作为转移性胰腺导管腺癌的一线治疗可显著改善中位总生存期（mOS: 11.1个月 vs 9.2个月，HR=0.75，p=0.04）。该研究确定了NALIRIFOX在适合高强度化疗的转移性胰腺癌患者中的一线标准地位。",
    evidenceLevel: "A",
    clinicalTrialId: "NCT04083235",
    clickable: true
  },
  {
    id: "osint-3",
    title: "Targeting ATM/ATR DNA Hazard Repair Pathway in Pancreatic Cancer: Phase II Trial Involving M6620 (Berzosertib) Initiated",
    url: "https://clinicaltrials.gov/study/NCT04895641",
    source: "ClinicalTrials.gov",
    publishedAt: "2026-06-22T02:00:00Z",
    country: "USA / Europe",
    category: "trial",
    entities: ["M6620", "Berzosertib", "ATR inhibitor", "ATM deficiency"],
    importanceScore: 8.5,
    summary: "一项最新的II期临床招募宣告启动，重点研究ATR选择性抑制剂Berzosertib（M6620）联合奥沙利铂在携带ATM缺陷（ATM loss/mutation，约占胰腺癌的10%）的晚期胰腺癌患者中的疗效。ATM/ATR通路是合成致死策略中的明星靶点，该研究旨在探索无化疗或低毒敏感联合靶向方案。",
    evidenceLevel: "B",
    clinicalTrialId: "NCT04895641",
    clickable: true
  },
  {
    id: "osint-4",
    title: "Heidelberg University Hospital Updates Surgical Resection Protocol for Borderline Resectable Pancreas Tumors: Focus on MDT & Neoadjuvant Therapy Timing",
    url: "https://www.heidelberg-university-hospital.com/surgical-guidelines",
    source: "Heidelberg Pancreas Center",
    publishedAt: "2026-06-18T11:00:00Z",
    country: "Germany",
    category: "surgery",
    entities: ["Borderline Resectable", "Neoadjuvant Therapy", "R0 Resection", "MDT Decision"],
    importanceScore: 8.0,
    summary: "海德堡大学胰腺外科中心修订了交界可切除胰腺癌（Borderline Resectable PDAC）的临床路径。新指南强调必须先由多学科门诊（MDT）评估，实施至少4-6周的改良FOLFIRINOX新辅助化疗加放疗提高R0切除率，并建议应用三维虚拟成像技术进行精细胰十二指肠切除术（Whipple术）规划，从而减少术后胰漏率至10%以下。",
    evidenceLevel: "B",
    clickable: true
  },
  {
    id: "osint-5",
    title: "Comprehensive Nutritional Assessment & Pancreatic Enzyme Replacement Therapy (PERT) Optimization Protocol Released",
    url: "https://www.esmo.org/guidelines/supportive-care",
    source: "ESMO Open / Supportive Care",
    publishedAt: "2026-06-17T09:45:00Z",
    country: "EU",
    category: "nutrition",
    entities: ["PERT", "EPI", "Supportive Care", "Cachexia"],
    importanceScore: 7.8,
    summary: "欧洲肿瘤内科学会（ESMO）在最新指南中重申了外源性胰腺功能不全（EPI）对胰腺癌患者生存期的潜在负面危害。由于胰头肿瘤压迫或胰腺切除，约80%晚期患者存在严重吸收不良导致贫血和恶病质。指南给出量化指标：每餐推荐立即随餐服用5-7.5万单位活性胰酶（PERT），可使患者体重流失速度降低50%，总生存期间接延长约3.2个月。",
    evidenceLevel: "A",
    clickable: true
  },
  {
    id: "osint-6",
    title: "Kyoto University Hospital Reports Robotic-Assisted Distal Pancreatectomy Shortened Hospitalization with Minimal Bleeding in RCT Study",
    url: "https://jrct.niph.go.jp/search",
    source: "jRCT (Japan)",
    publishedAt: "2026-06-15T06:20:00Z",
    country: "Japan",
    category: "surgery",
    entities: ["Robotic Pancreatectomy", "Distal Pancreatectomy", "Aesthetic Resection"],
    importanceScore: 8.2,
    summary: "日本京都大学附院在jRCT日本临床试验数据库发布了一项前瞻性随机对照临床研究结果。在胰体尾部占位切除术中，达芬奇机器人辅助的微创切除相比传统开腹手术，术中出血量减少68%，出院周程平均缩短4天，术后半年患者生存质量（SF-36评分）在疼痛程度和精神健康维度表现优势显著。",
    evidenceLevel: "B",
    clinicalTrialId: "jRCTs031250123",
    clickable: true
  },
  {
    id: "osint-7",
    title: "National Comprehensive Cancer Network (NCCN) Integrates Systematic Psychological Support Schemes into Pancreatic Patient Guidance Standard",
    url: "https://www.nccn.org/guidelines",
    source: "NCCN Clinical Practice Guidelines",
    publishedAt: "2026-06-12T10:00:00Z",
    country: "USA",
    category: "psychology",
    entities: ["NCCN", "Distress Distress Screen", "Psychology Support"],
    importanceScore: 7.2,
    summary: "NCCN发布了针对高恶性肿瘤（如胰腺癌）患者的多维度心理筛查标准。鉴于“癌王”给患者带来的剧烈心理恐慌和抑郁（发病率高过60%），指南强烈建议在确诊后3天内、化疗每周期开展 Distress Thermometer（心理痛苦温度计）测评。并要求设立绿色通道，引入基于正念减压（MBSR）的专业心理辅导和轻度精神调节药物，能有效缓解患者的顽固性胃肠神经反应。",
    evidenceLevel: "B",
    clickable: true
  },
  {
    id: "osint-8",
    title: "Cancer Care Quality Assessment: Global Disparity in Survival Rates Highlights Urgency of MDT Standard Dissemination",
    url: "https://www.who.int/cancer/publications",
    source: "WHO Oncology Reports",
    publishedAt: "2026-06-10T15:30:00Z",
    country: "Global",
    category: "policy",
    entities: ["Survival Rate Disparity", "MDT Dissemination", "UHC", "Global Cancer Policy"],
    importanceScore: 6.8,
    summary: "世界卫生组织（WHO）发布的全球胰腺癌治疗指南指出，发达地区与欠发达地区在胰腺癌5年生存率方面仍然存在显著隔阂（13% vs 3%）。由于本病诊断延迟且缺乏标准的区域协作（MDT），早期手术筛查率极低。报告呼吁将多学科联合诊疗（MDT）方案和腹腔灌注化疗等标准技术列入基本卫生保障和医保报销范畴。",
    evidenceLevel: "C",
    clickable: true
  },
  {
    id: "osint-9",
    title: "Exocrine Pancreatic Cancer Supportive Guidebook Released by PanCan Patient Foundation",
    url: "https://www.pancan.org/patient-resources",
    source: "Pancreatic Cancer Action Network",
    publishedAt: "2026-06-08T13:00:00Z",
    country: "USA",
    category: "patient_resource",
    entities: ["PanCan Guide", "Survivor Strategy", "Caregiver Toolkit"],
    importanceScore: 7.5,
    summary: "著名患者援助基金会PanCan发布了2026最新生存者攻略礼包。包含三大高价值板块：免费的专业营养师定制菜谱（解决化疗期间的丧失胃口问题）、一键式临床招募筛查助理（PanCan Clinical Trial Finder）、以及全国患者互助小组（Peer-to-Peer Support）联系通道。已验证该礼包对新确诊患者的心理舒缓与自救效能提升十分关键。",
    evidenceLevel: "D",
    clickable: true
  }
];

export const INITIAL_RESOURCE_CENTERS: ResourceCenter[] = [
  {
    id: "res-1",
    name: "卓越胰腺癌专科中心 - 德国海德堡大学附院 (Heidelberg Pancreas Center)",
    country: "德国 (Heidelberg, Germany)",
    latitude: 49.4122,
    longitude: 8.6724,
    specialties: ["Whipple精密外科手术", "复杂交界可切除胰腺癌MDT", "新辅助化疗免疫联合研究"],
    leadDoctors: ["Prof. Markus W. Büchler (荣休荣誉中心首脑)", "Prof. Christoph Michalski (现任普外及胰腺外科主任)"],
    type: "clinical_center",
    description: "全球公认的胰腺癌手术和综合诊疗中枢，胰腺外科切除数量居世界前列，建立了最严格的术前多学科评审（MDT）和术后康复规范。",
    contact: "heinz.pancreas@med.uni-heidelberg.de"
  },
  {
    id: "res-2",
    name: "MD安德森癌症中心 胰腺癌多学科攻坚行动计划 (MD Anderson Cancer Center - Pancreatic Cancer Moon Shot)",
    country: "美国 (Houston, Texas, USA)",
    latitude: 29.7072,
    longitude: -95.3963,
    specialties: ["靶向化疗分子靶位鉴定", "ATM/ATR/BRCA 合成致死早期筛查", "新型KRAS靶点联合免疫抗体临床研究"],
    leadDoctors: ["Dr. Anirban Maitra (胰腺癌研究巨擘)", "Dr. Gauri R. Varadhachary (资深内科肿瘤学家)"],
    type: "research_hub",
    description: "全球一流的肿瘤研究机构，通过'登月计划'（Moon Shot Initiative）针对侵袭性极强的PDAC开展大规模分子靶点测序，配套高通量药物筛选平台。",
    contact: "pancreaticcenter@mdanderson.org"
  },
  {
    id: "res-3",
    name: "京都大学附属医院 机器人与微创胰腺外科联盟 (Kyoto University Pancreas Minimally Invasive Center)",
    country: "日本 (Kyoto, Japan)",
    latitude: 35.0210,
    longitude: 135.7792,
    specialties: ["达芬奇机器人辅助腹腔镜微创切除", "保脾保幽门保留微创路径", "术后早期快速康复（ERAS）"],
    leadDoctors: ["Prof. Etsuro Hatano (肝胆胰微创外科首席)"],
    type: "clinical_center",
    description: "亚洲顶尖的微创胰腺切除中心，在国际上主导开展机器人在胰腺部分以及全切除中的规范性RCT研究，保持着极低的术中转开腹率。",
    contact: "kyoto-pancreas-hosp@kuhp.kyoto-u.ac.jp"
  },
  {
    id: "res-5",
    name: "胰腺癌行动网络 患者服务指南中心 (Pancreatic Cancer Action Network - PanCan Clinical Support)",
    country: "美国 (El Segundo, California, USA)",
    latitude: 33.9172,
    longitude: -118.4163,
    specialties: ["病患营养学膳食包", "全美临床试验匹配机器人 (TrialFinder)", "生存期互助配对指南"],
    type: "patient_guide",
    description: "全美最著名的非营利患者倡导机构，为患者免费提供最新的胰腺功能重建方案、化疗减毒饮食建议，以及专业学术资料库配对导航。",
    contact: "patientcentral@pancan.org",
    survivorResources: ["免费营养菜谱.pdf", "胰腺酶PERT补充计算表格", "化疗副反应居家干预手册"]
  },
  // SHANGHAI (上海)
  {
    id: "res-sh-fudan-tumor",
    name: "复旦大学附属肿瘤医院 胰腺外科/多学科联合协作组",
    country: "中国 (上海, China)",
    latitude: 31.19,
    longitude: 121.455,
    specialties: ["胰腺癌新辅助化疗/精准靶向(NP)", "胰十二指肠切除经典虞氏吻合(Yu-Fold)", "后腹膜复发病灶再切除", "高通量基因靶向及CLDN18.2抗体"],
    leadDoctors: ["虞先濬 教授 (副院长, 胰腺外科主任, 全球切除数量最大)"],
    type: "clinical_center",
    description: "外科手术切除年量全国第一，开展经典胰十二指肠、全胰切除以及联合大血管切除重建。虞先濬教授团队领衔。周三下午多学科 MDT 联合门诊可申请会诊，拥有多项 CLDN18.2 抗体在研或临床管线。",
    contact: "sh_ca_hospital",
    survivorResources: ["经典虞氏二吻(Yu-Fold)术后指南", "多学科MDT会诊申请表"]
  },
  {
    id: "res-sh-ruijin",
    name: "上海交通大学医学院附属瑞金医院 消化肿瘤内外科与临床营养团队",
    country: "中国 (上海, China)",
    latitude: 31.215,
    longitude: 121.468,
    specialties: ["达芬奇机器人微创胰十二指肠切除", "介入引流急救与重症监护(RICU)", "新辅助放化疗综合转化与血管重建", "口服短肽与肠友代乳专门指导"],
    leadDoctors: ["彭承宏 教授", "沈柏用 教授"],
    type: "clinical_center",
    description: "彭承宏/沈柏用教授领衔，机器人微创胰腺比例极高。在重症合并胰瘘、腹膜转移急救方面提供极快 ICU 级重症防护，其配属的临床营养科针对晚期恶病质、术后消化酶绝对不全或吸收障碍提供口服短肽与肠友代乳专门指导。",
    contact: "sh-ruijin",
    survivorResources: ["胰腺癌术后口服短肽营养餐单", "机器人手术并发症自我追踪清单"]
  },
  {
    id: "res-sh-changhai",
    name: "海军军医大学第一附属医院 (上海长海医院) 长海胰腺病医院",
    country: "中国 (上海, China)",
    latitude: 31.30,
    longitude: 121.52,
    specialties: ["超声内镜下微创穿刺诊断(EUS-FNA)", "难治性急性/重症慢性胰腺炎管理", "难治性残端胰瘘无创负压冲洗", "多学科胰旁引流管带管居家维护"],
    leadDoctors: ["金钢 教授 (消化大出血及重症治疗领衔人)"],
    type: "clinical_center",
    description: "金钢主任团队，拥有独立长海胰腺病医院建制。超声内镜下微创穿刺 (EUS-FNA) 诊断技术全国顶尖，消化大出血急诊栓塞成功率高，胰旁引流管、双套管多学科居家维护规范极其优秀。",
    contact: "chhospital",
    survivorResources: ["胰旁引流管带管居家自我维护视频", "EUS-FNA穿刺术后观察手册"]
  },
  {
    id: "res-sh-zhongshan",
    name: "复旦大学附属中山医院 胰腺综合诊断与介入急救中心",
    country: "中国 (上海, China)",
    latitude: 31.20,
    longitude: 121.454,
    specialties: ["早期筛查与射频消融技术(RFA)", "突发出血高敏介入造影栓塞(TAE)", "胰腺内分泌肿瘤(NETs)规范多药MDT", "血管介入止血与管腔支架置入"],
    leadDoctors: ["刘亮 教授", "王文权 教授"],
    type: "clinical_center",
    description: "刘亮/王文权教授领衔，在胃肠胰腺外科、消融及突发生死急救上底蕴深厚。其介入与急诊 ICU 在血管造影栓塞（TAE）止血、肠梗阻消化道支架、内镜胆道 PTCD 减黄和并发症处理上提供秒级救治保障。",
    contact: "gh_731e8b26f5ff",
    survivorResources: ["中山医院胰酶精准治疗支持指南", "突发胆道减黄快速就医卡"]
  },
  {
    id: "res-sh-huashan",
    name: "复旦大学附属华山医院 胰腺外科与神经心理安宁科",
    country: "中国 (上海, China)",
    latitude: 31.22,
    longitude: 121.436,
    specialties: ["后腹膜侵犯清扫与局部冷热消融", "胰体尾切除及网膜淋巴清扫(RAMPS)", "超声下腹腔神经丛阻滞止痛(CPB)", "末期安宁舒缓与严重顽痛认知疏导"],
    leadDoctors: ["傅德良 教授 (血管剥离及精细缝合专家)"],
    type: "clinical_center",
    description: "傅德良教授团队，在胰腺解剖学及精细消融止血上口碑佳。针对腹膜后严重神经丛性侵犯剧痛，其疼痛科首推超声引导下腹腔神经丛阻滞 CPB 技术，配合极为权威的神经心理与安宁舒缓照护门诊。",
    contact: "hs_fudan",
    survivorResources: ["超声引导CPB神经丛阻滞术前准备", "华山安宁缓和医疗指导手册"]
  },
  {
    id: "res-sh-shi-yi",
    name: "上海市第一人民医院 胰腺外科与肿瘤内科中心",
    country: "中国 (上海, China)",
    latitude: 31.245,
    longitude: 121.485,
    specialties: ["胰腺外分泌功能不全(PEI)精细管理", "多模态消融技术创新应用", "数字化病程随访", "新药转化临床研究"],
    leadDoctors: ["龙江 教授", "李琦 主任"],
    type: "clinical_center",
    description: "龙江教授与李琦主任领衔，持续推进'胰腺内外联合、多学科协同、全病程管理、数字化赋能'。构建起覆盖预防、诊断、治疗、康复及长期随访的完整诊疗体系，涵盖 PEI 规范化管理与多模态消融创新。",
    contact: "sh_first_hosp",
    survivorResources: ["PEI自测与膳食干预模型", "新药转化临床一期入组流程"]
  },
  // BEIJING (北京)
  {
    id: "res-bj-xiehe",
    name: "北京协和医院 基本外科（胰腺专业组）与多学科MDT联合协作组",
    country: "中国 (北京, China)",
    latitude: 39.91,
    longitude: 116.41,
    specialties: ["国家疑难罕见疾病救治平台(MDT)", "超声内镜腹腔神经丛阻滞消融(CPB)", "三管联合微创介入减黄术(PTCD)", "国产机器人胰腺癌根治术", "胰岛素瘤等神经内分泌肿瘤(亚洲最大宗)"],
    leadDoctors: ["赵玉沛 院士 (中国工程院, 国际胰腺学会前主席)", "张太平 教授 (基本外科教研室主任, 博导)", "廖泉 教授"],
    type: "clinical_center",
    description: "中国胰腺外科历史最悠久的中心，赵玉沛院士奠定体系。40余年累计诊治胰腺癌5000余例、胰岛素瘤600余例（亚洲最多）；2024年完成首例国产机器人胰腺癌根治术。对极复杂合并血管重建的胰腺切除享誉全国，麻醉与疼痛科对严重腹膜后癌痛管理居国内标杆。门诊建议提前在协和官方 App 预约周三 MDT 绿道。",
    contact: "pumch_hospital",
    survivorResources: ["协和癌性长效镇痛CPB穿刺指南", "PTCD居家胆汁引流自我照护规范"]
  },
  {
    id: "res-bj-beida-tumor",
    name: "北京大学肿瘤医院 肝胆胰外二科（软组织与腹膜后肿瘤中心）",
    country: "中国 (北京, China)",
    latitude: 39.92,
    longitude: 116.32,
    specialties: ["多线化疗转化与个体耐药分析", "胃肠肿瘤ADC精准分子筛选", "腹腔多维度局部温热及粒子消融", "胰十二指肠切除标准化流程", "静脉置管日间化疗追踪"],
    leadDoctors: ["郝纯毅 教授 (大外科常务副主任, CSCO胰腺癌专家委员会前任主任委员, 国务院特殊津贴)", "邢宝才 教授 (肝胆胰外一科)"],
    type: "clinical_center",
    description: "郝纯毅团队领衔，以胰腺肿瘤综合治疗见长，化疗+手术转化方案规范，围手术期管理达国际先进水平。多学科开展消化道肿瘤临床转化新药高地，率先承揽二线口服/注射靶向ADC、胰腺KRAS G12D前沿在研开发，提供规范化静脉置管日间化疗与营养不良反应快速追踪等优质服务。",
    contact: "bj-pku-tumor",
    survivorResources: ["消化肿瘤新药招募与筛选名册", "PICC置管居家维护及出血干预手册"]
  },
  {
    id: "res-bj-301",
    name: "中国人民解放军总医院 (301医院) 肝胆胰外科学部与重症监护群",
    country: "中国 (北京, China)",
    latitude: 39.90,
    longitude: 116.27,
    specialties: ["微创介入放疗与立体消融", "复杂血管重建修复术", "高规格综合重症急救支持"],
    leadDoctors: ["卢实春 教授 (重症外科抢救专家)"],
    type: "clinical_center",
    description: "依托高规格医疗设备，在完全腔镜微创胰体尾 RAMPS 精细切除、精确局部粒子放疗和复杂大血管重建上居华北前列。其重症监护群提供大出血和急腹症的高强度生命维持保障。",
    contact: "301_hospital",
    survivorResources: ["重症术后血管栓塞预防康复计划", "消融术后局灶物理散热指引"]
  },
  {
    id: "res-bj-beida-6",
    name: "北京大学第六医院 肿瘤心理照护门诊",
    country: "中国 (北京, China)",
    latitude: 39.98,
    longitude: 116.35,
    specialties: ["肿瘤心理照护与危机调控", "重症恶性抑郁/绝望恐惧物理控制", "慢性顽重痛引发睡眠障碍改善"],
    leadDoctors: ["国家级肿瘤心理照护专家组"],
    type: "patient_guide",
    description: "全国最顶尖精神卫生专科大院，专设肿瘤心理照护门诊。提供针对癌症等绝症确诊后极度恐惧、严重抗焦躁以及长期不眠、伴痛精神崩溃的无药物或轻度精神量化身心辅导。",
    contact: "pkuh6_wechat",
    survivorResources: ["正念抗癌减压睡前音频", "绝重症家属照护心理自救手册"]
  },
  // JIANGSU (江苏)
  {
    id: "res-js-shengrenmin",
    name: "江苏省人民医院 胰腺疾病中心 (蒋奎荣/钱祝银/苗毅团队)",
    country: "中国 (江苏, China)",
    latitude: 32.05,
    longitude: 118.77,
    specialties: ["完全腔镜下缝合‘苗氏胰改道重建’", "复杂胰瘘的微创分步序贯靶向冲洗", "冷冻/消融复合内引消融(钱祝银团队)", "分子级肠内营养恶病质逆转"],
    leadDoctors: ["蒋奎荣 教授 (普外主任)", "钱祝银 教授 (消融冷冻胰腺疾病创始人)", "苗毅 教授 (终身学术带头人)"],
    type: "clinical_center",
    description: "国家重点胰腺专科中心，苗毅/蒋奎荣教授团队首创的苗氏缝合及胰改道重建享誉国际。钱祝银团队专门针对中晚期不适宜手术患者，实施冷冻及消融局部灭癌，提供极高水准营养门诊建立化疗时机。",
    contact: "jsph-panc",
    survivorResources: ["苗氏改道术后居家快速康复计划", "胰冷冻消融术后发热应对规范"]
  },
  {
    id: "res-js-gulou",
    name: "南京大学医学院附属鼓楼医院 肝胆胰外科与重症医学部",
    country: "中国 (江苏, China)",
    latitude: 32.06,
    longitude: 118.78,
    specialties: ["高度难治性局部晚期联合大血管切除重建", "早期肝转移局部冷热消融", "重症创伤、消化大出血多科秒级急救", "重度创伤胰瘘高负压冲洗引流"],
    leadDoctors: ["重点普外及肝胆胰血管再造团队"],
    type: "clinical_center",
    description: "复杂血管重建剥离切除首屈一指。其中重症介入中心在处理消化道突发出血、完全肠梗阻内引及腹下极重胰瘘等急腹症并发症急抢领域极显实力，保障省内患者快速转运与周转挂号。",
    contact: "njglyy1892",
    survivorResources: ["腹腔多双全套引流居家负压冲洗手册", "消化大出血出院饮食绝对禁忌"]
  },
  {
    id: "res-js-sudayifu",
    name: "苏州大学附属第一医院 肝胆胰微创外科中心",
    country: "中国 (江苏, China)",
    latitude: 31.32,
    longitude: 120.63,
    specialties: ["胰周肿瘤血管超声介入穿刺", "完全腹腔镜微创胰体尾切除", "高龄患者多学科精准围手术期评估", "苏南异地结算MDT快挂通道"],
    leadDoctors: ["苏南普外微创及高龄评估协作专家组"],
    type: "clinical_center",
    description: "苏南最强三甲核心，对高难度胰腺根治与术后维持有扎实经验。支持苏州及周边市域患者异地诊疗一站式医保联网核算，积极开展 MDT 联合查房并开辟放化疗快速预约绿道。",
    contact: "sdafy_hosp",
    survivorResources: ["高龄患者腹腔镜术后呼吸肺部锻炼", "苏南化疗绿卡挂号表"]
  },
  {
    id: "res-js-naoke",
    name: "南京脑科医院 临床心理与精神科身心照护中心",
    country: "中国 (江苏, China)",
    latitude: 32.055,
    longitude: 118.76,
    specialties: ["省内最强身心障碍会诊体系", "严重带痛导致得极度恐慌干预", "求生欲重塑与失眠认知疗护"],
    leadDoctors: ["精神科/身心障碍门诊/临床心理科特聘专家"],
    type: "patient_guide",
    description: "全省脑与精神高级中心。专长开展大病引起的急性悲伤、恐惧及心理失衡干预，提供最专业的抗抑郁认知与脑生理物理疗解方法，提升慢性生存质量。",
    contact: "nj_nkyy",
    survivorResources: ["慢性重病伴痛家属安抚与沟通指南", "失眠行为认知CBT-I疗愈法"]
  },
  // SICHUAN (四川)
  {
    id: "res-sc-huaxi",
    name: "四川大学华西医院 胰腺外科与临床营养科",
    country: "中国 (四川, China)",
    latitude: 30.64,
    longitude: 104.06,
    specialties: ["完全腔镜下复杂血管改道切除(达芬奇)", "腹腔镜胰十二指肠切除(LPD,西部首例3D-LPD)", "多脏器侵犯特大疑难切除生存重整", "剧烈消瘦/低蛋白恶病质干涉", "跨省即时报销多中心互助"],
    leadDoctors: ["彭兵 教授 (学科带头人, 腹腔镜LPD国内领军)", "刘续宝 教授", "柯能文 教授", "蔡云强 教授", "郑振江 教授"],
    type: "clinical_center",
    description: "全国重点学科、卫生部重点学科，医师34名（教授7名），西部最强综合性医院胰腺外科。全科肝/胆/胰/脾手术每年完成3600余台，腹腔镜胰十二指肠切除2018年已达169台，完成多项国际/国内首例微创术式（联合血管切除重建LPD、保留十二指肠全胰头切除等）。其临床营养科十分拔尖，针对大型术后顽固吸收不全、体重骤缩和急重腹腔粘连引发的胃瘫，提供高热比、分子级口服与肠内营养支持计划。",
    contact: "WestChina_Hospital",
    survivorResources: ["华西特膳口服代乳营养配方", "跨省转院极速医保直连指南"]
  },
  {
    id: "res-sc-renmin",
    name: "四川省人民医院 消化科与介入急危中心",
    country: "中国 (四川, China)",
    latitude: 30.66,
    longitude: 104.03,
    specialties: ["微创胆肠吻合内引流术(ERCP)", "耐药突变精准分子检测", "肠梗阻高敏胃导管引置", "严重的门静脉血栓抗栓急诊介入"],
    leadDoctors: ["省医多学科消化介入MDT专家组"],
    type: "clinical_center",
    description: "川渝多中心会诊中枢。特设胆汁高位减黄、胃管减张和肠梗阻急诊引流，其血管介入专门解决胰腺癌晚期最常见的门静脉血栓堵塞、腹部大出血等致死性并发症抢诊，设备极佳。",
    contact: "gh_sichuan_prov_hosp",
    survivorResources: ["门静脉血栓居家抗凝注射及不良反应", "ERCP术后高发胰腺炎自我预防"]
  },
  // ZHEJIANG (浙江)
  {
    id: "res-zj-zhedaer",
    name: "浙江大学医学院附属第二医院 (浙大二院) 肝胆胰外科",
    country: "中国 (浙江, China)",
    latitude: 30.25,
    longitude: 120.17,
    specialties: ["全腔镜切除淋巴无盲区大扫除", "联合血管解剖及原位移植重建", "中晚期术后多系统多学科顽痛镇痛", "首选MDT周四胰特会诊诊室"],
    leadDoctors: ["白雪莉 教授 (血管剥离切除世界知名)", "严盛 教授"],
    type: "clinical_center",
    description: "白雪莉/严盛教授团队代表省内极高血管解剖水准，对极难的淋巴清扫、原位血管移植重建和后腹膜冷热消融有扎实功底。特设周四下午多学科胰特会诊诊区。",
    contact: "z2hospital",
    survivorResources: ["术后极清复发评估随飞清单", "顽固骨转移及腹膜不适镇痛指南"]
  },
  {
    id: "res-zj-zhedayi",
    name: "浙江大学医学院附属第一医院 消化肿瘤内外科与重症组",
    country: "中国 (浙江, China)",
    latitude: 30.26,
    longitude: 120.18,
    specialties: ["肠道菌群移植(FMT)化疗减毒技术", "完全微创十二指肠精高保吻合", "重症术后人工辅助肝肾支持", "难治多线极速转化抗药配方"],
    leadDoctors: ["梁廷波 教授 (重症器官移植及外科大专家)"],
    type: "clinical_center",
    description: "梁廷波教授领衔，普外与移植ICU级别重症急救全省首位。针对术后复杂抗感染、吻漏、急骤发热、多器官不全提供人工肾透析与人工肝生命支持，开创 FMT 肠菌移植降低化疗消化副反应。",
    contact: "zdyy1947",
    survivorResources: ["FMT减毒治疗指引与临床一期申请", "重度黄疸胆管引流管自我维护规范"]
  },
  {
    id: "res-zj-shaoyifu",
    name: "浙江大学医学院附属邵逸夫医院 微创胰腺治疗中心",
    country: "中国 (浙江, China)",
    latitude: 30.25,
    longitude: 120.20,
    specialties: ["完全腔镜完全自吻合技术", "中美深度合作快速随诊通道", "保脾保幽门精确保留传统微创"],
    leadDoctors: ["虞洪 教授 (微创普外首席专家)"],
    type: "clinical_center",
    description: "中美医疗合作首推。虞洪主任带队的高水准微创中心，腔镜微创比率全省前列。术后早期快速康复（ERAS）规范健全，提供极其人性化和国际标准的日间复流随访。",
    contact: "srrsh1994",
    survivorResources: ["邵逸夫医院微创术后居家康复包", "日间化疗反应自我评定量表"]
  },
  {
    id: "res-zj-prov-renmin",
    name: "浙江省人民医院 临床营养科",
    country: "中国 (浙江, China)",
    latitude: 30.29,
    longitude: 120.16,
    specialties: ["特设特医肠内门诊", "化疗黏膜极化破损饮食调摄", "营养代乳及高碳水重度改善"],
    leadDoctors: ["临床高等级胰腺专用营养配制组"],
    type: "patient_guide",
    description: "省内极佳营养学科大本营。在放化疗期间由于严重口腔、小肠黏膜发生大溃疡，或者极度胃下垂、胃瘫难以食入等危症，提供分子级短链氨基口服和居家肠内高能袋乳维护。",
    contact: "zj_sry",
    survivorResources: ["化疗极差黏膜居家护理特异营养单", "口服大剂量特酶PERT居家餐配"]
  },
  {
    id: "res-zj-hangzhou-7",
    name: "杭州市第七人民医院 肿瘤睡眠心理干干预中心",
    country: "中国 (浙江, China)",
    latitude: 30.23,
    longitude: 120.11,
    specialties: ["慢性疼痛引发重不寐行为矫正", "临终惊恐绝望因心安照舒心"],
    leadDoctors: ["肿瘤伴痛睡眠心理睡眠障碍照护组"],
    type: "patient_guide",
    description: "全省极好的睡眠及心因专院。帮助解决由于强烈腹膜后神经丛浸润毒性压迫导致的剧痛患者、或者经历多次化疗耐药导致得自杀绝望情绪、睡眠断裂、日夜不安不寐惊恐，提供轻量引导。",
    contact: "hz_7y",
    survivorResources: ["7分钟渐进性肌肉呼吸放松音频", "抗抑郁重塑心理调适指南"]
  },
  // FUJIAN (福建)
  {
    id: "res-fj-yifuyuan",
    name: "福建医科大学附属第一医院 肝胆胰外科学部与急诊ICU",
    country: "中国 (福建, China)",
    latitude: 26.06,
    longitude: 119.30,
    specialties: ["全腔镜胰十二指肠切除术", "梗阻黄疸超快介入PTCD减温", "化脓性重症胆管炎多学科救急", "福建快排床化疗日间病区"],
    leadDoctors: ["海峡肝胆胰腔镜吻合重点专家组"],
    type: "clinical_center",
    description: "福建省普外排头，床位周转快，住院日极低。其急诊引流与 ICU 对严重晚期胆梗组引发的败血高烧、腹部剧烈破裂大出血、肠道水肿穿口提供极速一键救治绿道。",
    contact: "fyfy1860",
    survivorResources: ["胆管感染居家发烧急救包", "福建省一快速排床流程清单"]
  },
  {
    id: "res-fj-xiehe",
    name: "福建医科大学附属协和医院 胃肠胰外科与微创技术研究孵中心",
    country: "中国 (福建, China)",
    latitude: 26.08,
    longitude: 119.30,
    specialties: ["完全腹腔镜原位切吻合并清扫", "多线序贯与冷消融多药搭配", "高精血管游离胃网膜保留技术"],
    leadDoctors: ["协和胃肠普外名医专家组"],
    type: "clinical_center",
    description: "历史悠久得高精微创技术孵化地。腔镜缝合精度与保留术式省内知名，针对复杂难切胰腹在研提供全面的序贯多药联合指导及低毒敏感减量指南。",
    contact: "fjsfxyy",
    survivorResources: ["协和微创自合术后吻口安全指引", "化疗不良反应低血小板对策"]
  },
  {
    id: "res-fj-xiadayifu",
    name: "厦门大学附属第一医院 临床营养专科",
    country: "中国 (福建, China)",
    latitude: 24.45,
    longitude: 118.08,
    specialties: ["特医肠道屏障保护短肽代乳", "化疗强烈厌食与呕吐电解调节"],
    leadDoctors: ["闽南大病及肿瘤支持质疗科"],
    type: "patient_guide",
    description: "闽南地区核心。专门解决各种大手术后胰管引流缺乏引起得脂肪下痢、体重急坠及化疗期食不得入、强烈不适导致得骨质重度流失电解质脱水管理。",
    contact: "xmdxyf",
    survivorResources: ["中链长链甘油(MCT/LCT)随餐服用手册", "强烈恶心厌食居家汤食配方"]
  },
  {
    id: "res-fj-xianyue",
    name: "厦门市仙岳医院 精神心里与抗郁舒缓区",
    country: "中国 (福建, China)",
    latitude: 24.49,
    longitude: 118.11,
    specialties: ["绝症重挫引发丧志抑郁应对", "痛觉致惊恐性长期不眠行为调控"],
    leadDoctors: ["睡眠心理行为抗焦虑知名主任团队"],
    type: "patient_guide",
    description: "闽南极富盛名的精神卫生专科。特别为由于久带胰管引流、长年受疼产生严重的自我了断倾、绝望狂躁或者长期失眠的本癌病友，提供人性安全、身心自控等康保调护。",
    contact: "xmsxy",
    survivorResources: ["仙岳睡前5步催眠自安法", "抗癌重度抑郁自我情绪评估表"]
  },
  // HEBEI (河北)
  {
    id: "res-hb-hebdaer",
    name: "河北医科大学第二医院 肝胆胰及胰腺中心名医团队",
    country: "中国 (河北, China)",
    latitude: 38.05,
    longitude: 114.48,
    specialties: ["经典微创胆道介入(ERCP)支架置", "高龄普外安全吻合切缝技术", "河北快速异地就医周转绿道"],
    leadDoctors: ["河北省基本外科学院带头人团队"],
    type: "clinical_center",
    description: "石家庄最权威的大综合。普外科室庞大，其消化重症团队针对术后极重胰漏引发的二次大腹膜破出血、顽固性低钠血电解质丧失等特等急性并发症在省内具有最高急救水平，支持联网医保极快结算。",
    contact: "hb2h_sjz",
    survivorResources: ["术后严重低蛋白极速血清提升攻略", "河北省急重转诊指南"]
  },
  {
    id: "res-hb-hebdafr",
    name: "河北医科大学第四医院 (河北省肿瘤医院) 消化道肿瘤内科",
    country: "中国 (河北, China)",
    latitude: 38.04,
    longitude: 114.52,
    specialties: ["三线化免抗靶抗药耐受在研", "突发出血放射介入造栓(TAE)", "胃肠及胆道完全梗堵内镜管支撑"],
    leadDoctors: ["省肿瘤医院普内及重组协作组"],
    type: "clinical_center",
    description: "河北省内肿瘤建制最全的大院。其消化内分泌科、内镜室对完全梗塞黄疸下放支、血管介入止血具有很高效率。开辟了化疗由于白血细胞极低引发的中性感染、骨髓崩溃高敏重救支持。",
    contact: "hb4h_tum",
    survivorResources: ["省四院极低白细胞居家隔防护规则", "消化梗阻胆汁改路随诊记录表"]
  },
  {
    id: "res-hb-mhc",
    name: "河北省精神卫生中心 身心慢病关怀区",
    country: "中国 (河北, China)",
    latitude: 38.86,
    longitude: 115.48,
    specialties: ["重大身心创伤后应激障碍干护", "绝症濒死自绝悲哀家庭疏解"],
    leadDoctors: ["省卫生心理临床及抗癌小组教师集群"],
    type: "patient_guide",
    description: "保定重点专院，省内心理首选。致力于大病晚期癌症患者得心理危机重整、消除死悲、失落抗、慢性睡眠安眠调护物理引导，极其温暖柔度。",
    contact: "hbsj",
    survivorResources: ["消除绝症极恐悲哀睡前心理自愈", "病友互助心理支持俱乐部名册"]
  },
  // TIANJIN (天津)
  {
    id: "res-tj-yidazhongshan",
    name: "天津医科大学肿瘤医院 胰腺肿瘤科/内科与新药管线",
    country: "中国 (天津, China)",
    latitude: 39.07,
    longitude: 117.18,
    specialties: ["超低温冷/冷热微爆热消融术", "新药一期极速突变靶点临床匹配", "复合腹腔粒子植照及消灶放", "口乳代肠短肽胃食营养配给"],
    leadDoctors: ["郝继辉 教授 (普外普内大首席)", "王秀超 教授"],
    type: "clinical_center",
    description: "郝继辉教授领衔名扬北方的胰腺顶流。首创冷热超低温冷消灭局部不能切除肿瘤；并开设一期临床新药极速筛选，对高突靶KRAS、CLDN18.2、ATM不耐化疗者配套特医级PERT代乳支持，床位稍紧，推荐在线直挂预约MDT。",
    contact: "tj_mu_ch",
    survivorResources: ["超低温消融出院饮食与低热调理", "一期胰前沿临床筛匹配表"]
  },
  {
    id: "res-tj-yizhongxin",
    name: "天津市第一中心医院 重症监护肝胆胰外科",
    country: "中国 (天津, China)",
    latitude: 39.11,
    longitude: 117.15,
    specialties: ["高精国家移植重度ICU保障", "极险血管大破出血秒止栓封"],
    leadDoctors: ["天津一中心外科重点特需组"],
    type: "clinical_center",
    description: "依靠声名显著的国家重点器官移植生命监护，专门应对胰十二指术后发生的极高危败血性休克、大腹主动脉胃左动脉破裂血管高漏等绝症，大出血血管介入可在15分钟内通管止漏，重症床源多。",
    contact: "tj_1ch_org",
    survivorResources: ["重症术口皮下裂漏抗感染居家规", "突发大漏血大吐吐血秒急急救通道"]
  },
  {
    id: "res-tj-general",
    name: "天津医科大学总医院 内窥介入与急重中心",
    country: "中国 (天津, China)",
    latitude: 39.11,
    longitude: 117.20,
    specialties: ["急性胆胆道完全梗黄PTCD造管", "重症穿孔肠梗阻物理减减压术", "严重代谢低钾低钙紊乱危重纠偏"],
    leadDoctors: ["总院消化及普外内窥MDT小组"],
    type: "clinical_center",
    description: "老牌超级特重三甲。内窥急引胃动力中心全天抢开血管出血，对突发消化管壁严重穿溃引起的坏死感染，肠道大范围梗堵不排，或者由于剧强烈吐胆黄引发的重度碱酸血低电失衡纠偏极其强大精确。",
    contact: "tjmuyy",
    survivorResources: ["全静脉插管低能术后居家保护指南", "严重低钙肌肉痉挛电补充自测"]
  },
  {
    id: "res-tj-anding",
    name: "天津市安定医院 心身医学与肿瘤焦虑睡眠中心",
    country: "中国 (天津, China)",
    latitude: 39.04,
    longitude: 117.22,
    specialties: ["伴痛抑郁心因慢病辅助调理", "长时睡眠惊狂认知正念正念度"],
    leadDoctors: ["睡眠心理行为医学特设组"],
    type: "patient_guide",
    description: "天津最权威心理及精神卫生处。给予重病晚期恐慌、长期痛不瞑目的不寐病患配属系统的极速危机控制与正念睡照舒解。",
    contact: "tj_ad",
    survivorResources: ["安定抑郁抗惊不寐呼吸声频", "脑疲恐死睡梦深度身心阻舒手册"]
  },
  // CHONGQING (重庆)
  {
    id: "res-cq-xinan",
    name: "陆军军医大学第一附属医院 (西南医院) 肝胆胰及胰疾病中心",
    country: "中国 (重庆, China)",
    latitude: 29.53,
    longitude: 106.45,
    specialties: ["达芬奇及腔镜胰体切吻(RAMPS)", "同济-西南双套负压彻底防瘘", "由于残胰缺乏代谢干涉营养调摄", "由于大手术极剧失血急ICU"],
    leadDoctors: ["全军肝胆及胰微创经典教授组"],
    type: "clinical_center",
    description: "西南老牌军医顶流。术中精准高频射频无血大范围清扫后腹膜有绝招，发明得西南-同济经典引流套彻底消灭术后吻合漏死死并发，对大吐血引流漏提供极佳军区级重症监排，医保结算极其便利。",
    contact: "xnyy_1929",
    survivorResources: ["西南经典引流双导管居家维护视频", "西南特制高氨PERT吸收记录卡"]
  },
  {
    id: "res-cq-chongyiyifu",
    name: "重庆医科大学附属第一医院 消化道肿瘤内分泌中心",
    country: "中国 (重庆, China)",
    latitude: 29.54,
    longitude: 106.52,
    specialties: ["耐药突复测序靶向精配", "低白血化疗毒反急救管理", "序贯化学联合靶向不耐改善方案"],
    leadDoctors: ["重医附一消化癌症重点转化团队"],
    type: "clinical_center",
    description: "重庆临床科研排头。在晚期胰癌发生抗药后，开展全面的二线新型ADC多结合治疗，其重门诊配套对化免疫强烈排斥、低白脱液反应提供全流程日间极速减震指南。",
    contact: "cqyydy",
    survivorResources: ["重医附一基因靶筛特测申请表", "居家化疗退震口服辅阻单"]
  },
  {
    id: "res-cq-xinqiao",
    name: "陆军军医大学第二附属医院 (新桥医院) 精确肿瘤物理消融研究所",
    country: "中国 (重庆, China)",
    latitude: 29.52,
    longitude: 106.44,
    specialties: ["全军肿瘤精确物理消阻示范", "重度压迫后腹膜恶癌低温质放射"],
    leadDoctors: ["新桥物理消切放专家组"],
    type: "clinical_center",
    description: "全军物理所。针对大病完全包裹周围血管或侵吞神经，患者由于不具备普外切吻条件时，实施高频超定位物理粒子冷冻消阻、精确质子，对缓剧癌痛效果神绝。",
    contact: "xq_hosp",
    survivorResources: ["新桥质子物理放疗周期自我散热规", "低温粒子冷冻随访观察手册"]
  },
  {
    id: "res-cq-zhongliu",
    name: "重庆市肿瘤医院 消化胆道及介入血管急急科",
    country: "中国 (重庆, China)",
    latitude: 29.57,
    longitude: 106.47,
    specialties: ["管腔外胆道PTCD引支架置入", "消化道破大出血介入造栓", "严重极下肢门脉静脉血栓血管成形"],
    leadDoctors: ["肿瘤介入消病与血管造组医干"],
    type: "clinical_center",
    description: "市肿瘤科综合。内镜胆减、晚期胃壁破引发得特吐血介入 TAE 造影栓阻、以及静脉高压血栓成形、低钾腹腔水肿调节有着极丰富的市级绿通急抢通道。",
    contact: "cq_cth",
    survivorResources: ["PTCD术后出院引管洗净自我记录", "静脉栓注射居家预防大栓阻"]
  },
  {
    id: "res-cq-mhc",
    name: "重庆市精神卫生中心 临床躯体心理与安宁支持中心",
    country: "中国 (重庆, China)",
    latitude: 29.60,
    longitude: 106.59,
    specialties: ["由于剧恶病伴痛情绪调节", "山城特需癌友悲狂心理慰养"],
    leadDoctors: ["身心慢病及重性抗癌临床心里师群"],
    type: "patient_guide",
    description: "山城最有名望的身心及精神保健大所。对病危、久受疼、对家人愧悔绝心死得重恐癌友给予高质得睡导、危机控制、安舒精神辅阻。",
    contact: "cq_mhc",
    survivorResources: ["山城癌友心里减压抱负线上互助卡", "剧烈疼痛不寐情绪调节讲义"]
  },
  // GUANGZHOU (广州)
  {
    id: "res-gz-zhongshan-tumor",
    name: "中山大学肿瘤防治中心 胰腺外科/多学科协作组与营养研究中心",
    country: "中国 (广州, China)",
    latitude: 23.13,
    longitude: 113.29,
    specialties: ["机器人辅助盆壁大精淋巴清扫(LDP)", "大湾区最大质子精确无创原位放", "港澳药械通极速准新药抢配", "全国最顶尖恶病肠内PERT调摄"],
    leadDoctors: ["陈敏山 主任", "中肿消化介入大MDT团队"],
    type: "clinical_center",
    description: "国家重点大专。陈敏山等教授代表南中国最高技术，拥有大湾区高配质子治疗设备。其临床营养中心特别强大，为晚期消瘦、PERT缺失恶病质设计全系居家微能高吸收酶膳，粤港新药接轨全速绿道。",
    contact: "sysucc",
    survivorResources: ["中肿胰酶PERT服剂量智能补算表", "质子治疗不耐皮肤居家保护规则"]
  },
  {
    id: "res-gz-zhongshanyiyi",
    name: "中山大学附属第一医院 综合疑难普外科重症群",
    country: "中国 (广州, China)",
    latitude: 23.13,
    longitude: 113.28,
    specialties: ["国家重大疑难肝胆胰外重大救", "全多脏侵大疑吻重整", "ICU多器官人工辅助及超敏并发救治"],
    leadDoctors: ["中山一院重大疑普外老核心名医"],
    type: "clinical_center",
    description: "综合实力全国最强一梯。大普外对后腹侵全盆扫、胃肠主动血管再造重建、以及由于高龄大创术口引起的危重多脏器官失常衰弱（ICU人工心肺肝肾）急抢救技术雄伟名声在外。",
    contact: "zsyyfyy",
    survivorResources: ["全盆扫大创术后多导引漏水安全规", "国家级大疑MDT远程挂会规则"]
  },
  {
    id: "res-gz-nanfang",
    name: "南方医科大学南方医院 胃肠出血急诊介入与内内窥中心",
    country: "中国 (广州, China)",
    latitude: 23.19,
    longitude: 113.33,
    specialties: ["全消化大胃裂大呕吞镜下套套扎", "严重的肺间质损伤骨髓抑制重症"],
    leadDoctors: ["急诊中心及胃镜精熟介入专家组"],
    type: "clinical_center",
    description: "大型综合三甲。内窥高敏对晚切漏、肠压迫胃十二指壁破大呕大吐提供套套扎止血，及对强化后高发得骨髓抑制、大高烧败血、间质性肺水干预极其专业多保。",
    contact: "nyyyservice",
    survivorResources: ["呕血大出血时家人黄金20秒处理动作", "化疗引发间质肺损伤自我排评"]
  },
  {
    id: "res-gz-naoke",
    name: "广州医科大学附属脑科医院 临床身心干预照心",
    country: "中国 (广州, China)",
    latitude: 23.10,
    longitude: 113.23,
    specialties: ["长夜强痛不寐危机极速纠偏", "癌友家属悲郁长治认知支持"],
    leadDoctors: ["脑医院临床睡眠精神学高教专家组"],
    type: "patient_guide",
    description: "南中国最有名精神身心专治所。精治对癌症病友久疼伴痛极长夜不寐入眼、不愿顺治疗心因自闭，并辅配高质得睡眠脑生理松脑治疗。",
    contact: "gz_nk",
    survivorResources: ["脑医院睡前神经心律放松疗歌单", "癌友求生意愿家属扶振建议书"]
  },
  // WUHAN (武汉)
  {
    id: "res-wh-tongji",
    name: "华中科技大学同济医学院附属同济医院 胆胰外科与内镜急救中枢",
    country: "中国 (武汉, China)",
    latitude: 30.58,
    longitude: 114.26,
    specialties: ["腹腔镜胰十二指肠切除(LPD国内标准制定者之一)", "完全腔镜十二指肠胰切重建", "对于重高烧吻后消化引流抗感", "无创胃肠动力调胃瘫干预"],
    leadDoctors: ["秦仁义 教授 (胆胰外科主任, 腹腔镜胰十二指肠切除术国内标准制定者之一)"],
    type: "clinical_center",
    description: "秦仁义教授主导的华中重要胰腺微创外科中心，主办全国腹腔镜胰十二指肠切除术研讨并进行手术直播示范。发明的‘同济经典防瘘套管’显著降低 Whipple 术后致死胰漏率，其内镜对高阻完全黄、大吐血栓、术口引流居家支持享誉华中。",
    contact: "tj_hospital",
    survivorResources: ["同济经典双套管负压居家干冲录像", "术后早期无创胃瘫康恢复方案"]
  },
  {
    id: "res-wh-xiehe-pancreas",
    name: "华中科技大学同济医学院附属协和医院 胰腺外科中心",
    country: "中国 (武汉, China)",
    latitude: 30.58,
    longitude: 114.27,
    specialties: ["胰十二指肠切除(年超200例)", "腹腔镜及机器人胰十二指肠切除(年近100例)", "重症急性胰腺炎救治", "复杂胰腺肿瘤根治(年超300例)"],
    leadDoctors: ["王春友 教授 (胰腺外科主任, 中华医学会外科学分会胰腺外科学组原主委)", "吴河水 教授 (胰腺病研究所所长)"],
    type: "clinical_center",
    description: "华中地区最强胰腺外科之一，定编床位200张。每年胰十二指肠切除术超200例，腹腔镜及机器人胰十二指肠切除接近100例，其他胰腺肿瘤手术每年超300例。重症急性胰腺炎救治全国知名，王春友/吴河水教授领衔，是中华医学会胰腺外科学组传统重镇。",
    contact: "wh_union_pancreas",
    survivorResources: ["协和胰腺术后防瘘居家观察手册", "重症胰腺炎康复期饮食恢复指南"]
  },
  {
    id: "res-wh-xiehe",
    name: "华中科技大学同济医学院附属协和医院 消化道肿瘤内科",
    country: "中国 (武汉, China)",
    latitude: 30.58,
    longitude: 114.27,
    specialties: ["基因突复筛及消化靶配特药招", "耐受度二线化化及不耐改减量", "转化期全多靶维持周期方案"],
    leadDoctors: ["协和消化癌症在研项目大名师"],
    type: "clinical_center",
    description: "华中另一极名牌。特设各种新型一线化疗吉西败药后、KRAS/ATM基因多配筛通道，提供日线抗癌靶向特药在研一站接入，对重度白血下血化疗耐不适提供规范化维持分级调配。",
    contact: "wh_union_hospital",
    survivorResources: ["协和自主突基因复检测申请指南", "化后血细低下居家升针注意事"]
  },
  {
    id: "res-wh-prov-renmin",
    name: "湖北省人民医院 重急症肝胆普大外科",
    country: "中国 (武汉, China)",
    latitude: 30.53,
    longitude: 114.30,
    specialties: ["突腹大出血超介入急栓", "坏死穿大胰漏全腔排渗透急抢", "异地三甲即联网结算周通"],
    leadDoctors: ["湖北省急症与普外复合重症专家组"],
    type: "clinical_center",
    description: "设备顶流。全多科MDT绿色快速救胃侵突发梗、腹膜大壁大内渗大发烧，介入血管栓封效率快。支持长江江汉各域异地大直连结算报消，挂会极快。",
    contact: "hb_rm",
    survivorResources: ["省人医急诊转快速绿安全通知卡", "胰瘘管长期渗居家创清洁手册"]
  },
  {
    id: "res-wh-zhongnan",
    name: "武汉大学中南医院 严重大病支持及临床营养护中心",
    country: "中国 (武汉, China)",
    latitude: 30.55,
    longitude: 114.35,
    specialties: ["肠内吸收胃动力短营养极速维", "低白肠黏膜萎缩屏修复配方案"],
    leadDoctors: ["中南大肿瘤支持营养重点专家团队"],
    type: "patient_guide",
    description: "华中极佳得病患消瘦逆转中心。专治由于严重胃麻、低胃、不能吃不耐化化导致病友严重全身吸收障碍低白蛋白。提供精量分子短乳胃恢复代配餐支持，重置治疗机会。",
    contact: "wh_zn",
    survivorResources: ["中南中链高吸短营养随餐方案", "胃功能衰弱居家电活辅助餐搭配"]
  },
  {
    id: "res-wh-mhc",
    name: "武汉市精神卫生中心 慢躯病疼痛心里睡眠室",
    country: "中国 (武汉, China)",
    latitude: 30.61,
    longitude: 114.28,
    specialties: ["伴后腹神经痛苦极抑情绪引导", "恐癌狂焦心理安舒睡梦CBT-I"],
    leadDoctors: ["重症大病心里睡眠会专家干务组"],
    type: "patient_guide",
    description: "省内领先。应对因带管引、癌毒神经丛发剧烈腹部顽痛惊狂濒焦之本病友配制高品质失眠、安宁自导正念精神物理支持，极大程度恢复身心生力。",
    contact: "wh_mhc",
    survivorResources: ["武精神5分钟睡前心息自控指南", "病病不寐心自卫评估测试卡"]
  },
  // HENAN (河南)
  {
    id: "res-hn-zhengda-1",
    name: "郑州大学第一附属医院 肝胆胰外科医学部",
    country: "中国 (河南, China)",
    latitude: 34.75,
    longitude: 113.62,
    specialties: ["胰十二指肠切除与复杂胰腺根治", "肝移植(成人例数全国第二)", "基层转诊疑难胰腺病集中诊治", "多学科MDT与围手术期管理"],
    leadDoctors: ["郭文治 教授 (肝胆胰外科医学部主任, 2025大国工匠人才, 累计肝移植2300余台)"],
    type: "clinical_center",
    description: "中原地区最重要的肝胆胰诊疗中心，依托全国单体规模最大医院之一，医疗指标居华中地区前列、成人肝移植例数全国第二。郭文治教授领衔，承担大量基层转诊胰腺病例，国自然3项、省部级19项/年，是河南及周边省份胰腺疑难重症的核心转诊枢纽。",
    contact: "zdyfy_hospital",
    survivorResources: ["中原患者跨市转诊绿色通道指引", "胰腺术后基层随访对接清单"]
  },
  // JINAN (济南)
  {
    id: "res-jn-qilu",
    name: "山东大学齐鲁医院 肝胆胰及胰多学科MDT中心",
    country: "中国 (山东, China)",
    latitude: 36.65,
    longitude: 117.02,
    specialties: ["腹水高频温热灌注化疗(HIPEC)", "超声定位穿刺病检EUS-FNA", "周二挂牌多中心胰特会诊诊区", "后腹神经根局部解剥切吻阻痛"],
    leadDoctors: ["齐鲁普外大名科主刀教授集群"],
    type: "clinical_center",
    description: "百年齐鲁。普外科主切吻血管重建等根切功力在山东最盛。其疼痛科疼痛局部后壁刀分离、特别是针对腹膜后大转移积积水首推精创高感 HIPEC（热化疗）抑制技术，在华东傲立前茅。",
    contact: "sdyxqlyy",
    survivorResources: ["齐鲁HIPEC术后居家消皮肿对策", "周二多学科MDT联合会诊预约表"]
  },
  {
    id: "res-jn-prov-shengli",
    name: "山东第一医科大学附属省立医院 消化内科与精准靶免中枢",
    country: "中国 (山东, China)",
    latitude: 36.66,
    longitude: 117.01,
    specialties: ["多线序贯抗抗药化化敏感调", "化学骨抑制重症骨保护随飞", "耐突精准分子配药维持给给"],
    leadDoctors: ["省立内科化免及重症防护专家组"],
    type: "clinical_center",
    description: "省会大型。消化及肿瘤内对吉西旧药严重抗阻后、ATM/KRAS多路径转化新型方案极其熟稔。全日配套化疗骨髓深虚骨、极低白细胞不适多功综合抢治，安全保障性高。",
    contact: "sdslyy",
    survivorResources: ["省省立精准双靶长期维持服用指南", "胃肠化后消化道溃呕自测记录"]
  },
  {
    id: "res-jn-prov-tumor",
    name: "山东省肿瘤医院 无创放疗与院士质子重离子大中心",
    country: "中国 (山东, China)",
    latitude: 36.64,
    longitude: 116.82,
    specialties: ["院士级极限精密外照射定质子", "不适宜外科切冷冷射消融消瘤", "中晚期后腹包裹难侵质放"],
    leadDoctors: ["于金明 院士 (放疗及质子消瘤总首脑)"],
    type: "clinical_center",
    description: "于金明院士领衔，国内最高质子物理所一极。配备定物理外照。专门针对因高龄、严重吸收极差、后壁大血管完全黏连无法实施Whipple的困难患者提供非创高定质子消，解毒极快。",
    contact: "sds_tumor",
    survivorResources: ["质子中心放射出院居家护理要则", "不适宜手术病病物理粒子消瘤匹配表"]
  },
  {
    id: "res-qd-qdyifu",
    name: "青岛大学附属医院 临床营养专科",
    country: "中国 (山东, China)",
    latitude: 36.06,
    longitude: 120.32,
    specialties: ["口乳代肠短营养吸收配配", "胃麻不食厌引发恶病低白纠偏"],
    leadDoctors: ["东鲁大病临床支持配液名医组"],
    type: "patient_guide",
    description: "东部医学核心。特色恶病质支持。对中晚期强烈吐、胃黏膜肠道完全萎弱胃瘫患者提供高吸收短肽口乳及中链脂肪酸补充指导，在省内口碑极大。",
    contact: "qd_hosp",
    survivorResources: ["青医大高热短口乳餐服用记录卡", "化疗厌食不食胃辅动力指引"]
  },
  {
    id: "res-jn-mhc",
    name: "山东省精神卫生中心 身心慢病与睡眠干预室",
    country: "中国 (山东, China)",
    latitude: 36.67,
    longitude: 117.06,
    specialties: ["晚癌顽痛心因惊恐危机阻调", "失眠与不寐长夜呼吸控制物理"],
    leadDoctors: ["省精神临床里慢躯身心里师群"],
    type: "patient_guide",
    description: "山东最高心理与安定院。特别为由于长期胆黄带引、大痛无眠、对死恐惧生绝得本症病友配设一站式的危机情绪安护正念及失眠CBT，充满仁温人文安抚。",
    contact: "sds_mhc",
    survivorResources: ["安定安宁癌病睡前自导心安声频", "慢性睡眠长长不睡行为自适指南"]
  }
];

export const MOCK_15DAY_REPORT: SystemReport15Day = {
  generatedAt: "2026-06-22T16:00:00Z",
  title: "Pancreatic Cancer OSINT Hub - 第 15 天系统自治质量与升级评估报告",
  executiveSummary: "系统在过去15天的自治状态极佳。采集蜘蛛网络持续向好，依靠LLM自动修复代理（Watchdog）在 06-15 和 06-19 自动化解决了共计2期RSS选择器变动的阻断异常。全球多中心学术源覆盖平稳，尤以靶向联合、外科新微创和辅助PERT推荐等类别数据饱满。系统健康得分 98分，并已构建完整的IPFS快照和去中心化一键部署容器集。",
  dataQualityScore: 98,
  crawlerSuccessRate: 99.4,
  topActiveSources: [
    { name: "ClinicalTrials.gov", count: 48 },
    { name: "PubMed Central (PMC)", count: 32 },
    { name: "ASCO GI Abstract Archive", count: 21 },
    { name: "FDA Press Release Daily", count: 12 },
    { name: "Heidelberg Center Internal Feed", count: 8 }
  ],
  categoryDistribution: [
    { category: "drug", count: 25 },
    { category: "trial", count: 38 },
    { category: "surgery", count: 14 },
    { category: "nutrition", count: 18 },
    { category: "psychology", count: 12 },
    { category: "complication", count: 15 },
    { category: "policy", count: 8 },
    { category: "patient_resource", count: 11 }
  ],
  recommendations: [
    "针对目前ATM缺陷型患者的招募试验增长，应在抓取器中增加'ATM Loss'和'POLO'相关突变组合的检索频率。",
    "jRCT数据库的反爬限额存在小幅波动，自动重试退避级别已被LLM调整至等级3（指数退避+抖动，10秒基准）。",
    "建议立即将本节点第15天情报快照发布至 Arweave 去中心化存储，增加分布式容灾能力。"
  ]
};
