begin;

create extension if not exists pgcrypto;

create or replace function public.validate_source_backed_scale_metrics(metrics jsonb)
returns boolean
language sql
immutable
as $$
  select
    case
      when jsonb_typeof(metrics) <> 'array' then false
      when exists (
        select 1
        from jsonb_array_elements(metrics) as item
        where not (
          item ? 'metric_key'
          and item ? 'name'
          and item ? 'value'
          and item ? 'unit'
          and item ? 'period'
          and item ? 'scope'
          and item ? 'definition'
          and item ? 'source_urls'
          and item ? 'source_type'
          and item ? 'verification_status'
          and item ? 'confidence'
        )
      ) then false
      else true
    end;
$$;

create table if not exists public.app_settings (
  setting_key text primary key,
  setting_value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.patient_profiles (
  profile_uid text primary key,
  city text not null default '',
  mutations text[] not null default '{}'::text[],
  ihc_results text not null default '',
  regimen text not null default '',
  efficacy text not null default '',
  summary text not null default '',
  last_updated timestamptz not null default now()
);

create table if not exists public.watchdog_events (
  event_id bigint generated by default as identity primary key,
  event_type text not null,
  severity text not null default 'info',
  message text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.system_reports (
  report_id bigint generated by default as identity primary key,
  report_type text not null,
  title text not null,
  generated_at timestamptz not null default now(),
  executive_summary text not null default '',
  data_quality_score numeric(5, 2) not null default 0,
  crawler_success_rate numeric(5, 2) not null default 0,
  payload jsonb not null default '{}'::jsonb
);

create table if not exists public.geo_regions (
  region_key text primary key,
  region_name text not null,
  region_rank integer not null default 0,
  source_urls text[] not null default '{}'::text[],
  updated_at timestamptz not null default now()
);

create table if not exists public.geo_countries (
  country_key text primary key,
  region_key text not null references public.geo_regions(region_key) on delete cascade,
  country_name text not null,
  iso_code text not null default '',
  source_urls text[] not null default '{}'::text[],
  updated_at timestamptz not null default now()
);

create table if not exists public.geo_cities (
  city_key text primary key,
  country_key text not null references public.geo_countries(country_key) on delete cascade,
  city_name text not null,
  latitude numeric(10, 6) not null,
  longitude numeric(10, 6) not null,
  data_quality text not null default 'public',
  source_urls text[] not null default '{}'::text[],
  updated_at timestamptz not null default now(),
  constraint geo_cities_data_quality_check check (data_quality in ('public', 'estimated', 'mixed', 'unverified'))
);

create table if not exists public.resource_centers (
  center_key text primary key,
  city_key text not null references public.geo_cities(city_key) on delete cascade,
  center_name text not null,
  center_type text not null default 'clinical_center',
  explicit_category text not null default 'treatment',
  latitude numeric(10, 6) not null,
  longitude numeric(10, 6) not null,
  specialties text[] not null default '{}'::text[],
  lead_doctors text[] not null default '{}'::text[],
  description text not null default '',
  contact text not null default '',
  survivor_resources text[] not null default '{}'::text[],
  source_urls text[] not null default '{}'::text[],
  data_quality text not null default 'public',
  last_verified_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint resource_centers_explicit_category_check check (explicit_category in ('treatment', 'complication', 'psychology', 'nutrition')),
  constraint resource_centers_data_quality_check check (data_quality in ('public', 'estimated', 'mixed', 'unverified')),
  constraint resource_centers_center_type_check check (center_type in ('clinical_center', 'research_hub', 'patient_guide'))
);

create table if not exists public.hospital_departments (
  department_id bigint generated by default as identity primary key,
  city_key text not null references public.geo_cities(city_key) on delete cascade,
  center_key text references public.resource_centers(center_key) on delete set null,
  hospital_name text not null,
  department_name text not null,
  resource_type text not null,
  capability_tags text[] not null default '{}'::text[],
  complication_tags text[] not null default '{}'::text[],
  scale_metrics jsonb not null default '[]'::jsonb,
  data_quality text not null default 'public',
  source_urls text[] not null default '{}'::text[],
  last_verified_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint hospital_departments_resource_type_check check (resource_type in ('treatment', 'complication', 'psychology', 'nutrition')),
  constraint hospital_departments_data_quality_check check (data_quality in ('public', 'estimated', 'mixed', 'unverified')),
  constraint hospital_departments_scale_metrics_check check (public.validate_source_backed_scale_metrics(scale_metrics))
);

create table if not exists public.department_public_accounts (
  account_id bigint generated by default as identity primary key,
  department_id bigint references public.hospital_departments(department_id) on delete cascade,
  center_key text references public.resource_centers(center_key) on delete cascade,
  platform text not null default 'wechat',
  account_name text not null,
  account_handle text not null default '',
  source_url text not null default '',
  verified_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.resource_heat_snapshots (
  snapshot_id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_key text not null,
  window_label text not null,
  public_signal_heat integer not null default 0,
  wechat_activity_heat integer not null default 0,
  academic_activity_heat integer not null default 0,
  trial_activity_heat integer not null default 0,
  patient_discussion_heat integer not null default 0,
  data_quality text not null default 'public',
  source_urls text[] not null default '{}'::text[],
  captured_at timestamptz not null default now(),
  constraint resource_heat_snapshots_public_signal_heat_check check (public_signal_heat between 0 and 100),
  constraint resource_heat_snapshots_wechat_heat_check check (wechat_activity_heat between 0 and 100),
  constraint resource_heat_snapshots_academic_heat_check check (academic_activity_heat between 0 and 100),
  constraint resource_heat_snapshots_trial_heat_check check (trial_activity_heat between 0 and 100),
  constraint resource_heat_snapshots_patient_heat_check check (patient_discussion_heat between 0 and 100),
  constraint resource_heat_snapshots_data_quality_check check (data_quality in ('public', 'estimated', 'mixed', 'unverified'))
);

create table if not exists public.resource_source_links (
  link_id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_key text not null,
  source_title text not null default '',
  source_url text not null default '',
  source_type text not null default '',
  evidence_note text not null default '',
  verification_status text not null default 'unverified',
  confidence text not null default 'medium',
  created_at timestamptz not null default now(),
  constraint resource_source_links_verification_status_check check (verification_status in ('verified', 'cross_checked', 'single_source', 'conflicting', 'unverified')),
  constraint resource_source_links_confidence_check check (confidence in ('high', 'medium', 'low'))
);

alter table public.app_settings enable row level security;
alter table public.patient_profiles enable row level security;
alter table public.watchdog_events enable row level security;
alter table public.system_reports enable row level security;
alter table public.geo_regions enable row level security;
alter table public.geo_countries enable row level security;
alter table public.geo_cities enable row level security;
alter table public.resource_centers enable row level security;
alter table public.hospital_departments enable row level security;
alter table public.department_public_accounts enable row level security;
alter table public.resource_heat_snapshots enable row level security;
alter table public.resource_source_links enable row level security;

create policy "geo_regions_read_public"
  on public.geo_regions
  for select
  using (true);

create policy "geo_countries_read_public"
  on public.geo_countries
  for select
  using (true);

create policy "geo_cities_read_public"
  on public.geo_cities
  for select
  using (true);

create policy "resource_centers_read_public"
  on public.resource_centers
  for select
  using (true);

create policy "hospital_departments_read_public"
  on public.hospital_departments
  for select
  using (true);

create policy "department_public_accounts_read_public"
  on public.department_public_accounts
  for select
  using (true);

create policy "resource_heat_snapshots_read_public"
  on public.resource_heat_snapshots
  for select
  using (true);

create policy "resource_source_links_read_public"
  on public.resource_source_links
  for select
  using (true);

create policy "system_reports_read_public"
  on public.system_reports
  for select
  using (true);

commit;

