begin;

create table if not exists public.news_source_registry (
  source_key text primary key,
  source_name text not null,
  source_type text not null,
  source_url text not null,
  authority_score numeric(5, 2) not null default 0,
  cadence_minutes integer not null default 5,
  active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.news_source_collections (
  collection_key text primary key,
  source_key text not null references public.news_source_registry(source_key) on delete cascade,
  adapter_name text not null,
  adapter_config jsonb not null default '{}'::jsonb,
  enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.news_collection_runs (
  run_id bigint generated by default as identity primary key,
  source_key text not null references public.news_source_registry(source_key) on delete cascade,
  status text not null default 'pending',
  window_start timestamptz,
  window_end timestamptz,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  emitted_count integer not null default 0,
  duplicate_count integer not null default 0,
  error_count integer not null default 0,
  run_meta jsonb not null default '{}'::jsonb,
  error_message text not null default '',
  constraint news_collection_runs_status_check check (status in ('pending', 'running', 'success', 'partial_failure', 'failure'))
);

create table if not exists public.news_normalized_items (
  item_key text primary key,
  source_key text not null references public.news_source_registry(source_key) on delete cascade,
  collection_run_id bigint references public.news_collection_runs(run_id) on delete set null,
  seed_kind text not null default 'feed_item',
  review_status text not null default 'pending',
  title text not null,
  url text not null,
  source_title text not null default '',
  source_type text not null default '',
  published_at timestamptz,
  observed_at timestamptz not null default now(),
  freshness_minutes integer not null default 0,
  window_label text not null default '24h',
  center_priority boolean not null default false,
  topic_tags text[] not null default '{}'::text[],
  content_tags text[] not null default '{}'::text[],
  evidence_level text not null default 'D',
  region_key text not null default '',
  country_key text not null default '',
  city_key text not null default '',
  treatment_center_key text not null default '',
  summary text not null default '',
  patient_summary text not null default '',
  evidence_refs jsonb not null default '[]'::jsonb,
  risk_flags text[] not null default '{}'::text[],
  dedupe_key text not null default '',
  normalized_payload jsonb not null default '{}'::jsonb,
  constraint news_normalized_items_seed_kind_check check (seed_kind in ('feed_item', 'seed_candidate', 'intelligence_event', 'source_metadata_only', 'reject')),
  constraint news_normalized_items_review_status_check check (review_status in ('pending', 'needs_human_review', 'approved', 'rejected'))
);

create table if not exists public.news_review_actions (
  action_id bigint generated by default as identity primary key,
  item_key text not null references public.news_normalized_items(item_key) on delete cascade,
  action text not null,
  reviewer_id text not null default '',
  reviewed_at timestamptz not null default now(),
  notes text not null default '',
  constraint news_review_actions_action_check check (action in ('approve', 'keep', 'merge', 'reject', 'request_enrichment'))
);

create table if not exists public.intelligence_events (
  event_key text primary key,
  item_key text not null references public.news_normalized_items(item_key) on delete cascade,
  title text not null,
  source_url text not null,
  source_title text not null default '',
  published_at timestamptz,
  review_status text not null default 'approved',
  evidence_level text not null default 'D',
  professional_summary text not null default '',
  patient_summary text not null default '',
  patient_relevance text not null default '',
  potential_value text not null default '',
  potential_risk text not null default '',
  uncertainty_note text not null default '',
  region_key text not null default '',
  country_key text not null default '',
  city_key text not null default '',
  treatment_center_key text not null default '',
  topic_tags text[] not null default '{}'::text[],
  content_tags text[] not null default '{}'::text[],
  source_evidence jsonb not null default '[]'::jsonb,
  metrics jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.news_source_registry enable row level security;
alter table public.news_source_collections enable row level security;
alter table public.news_collection_runs enable row level security;
alter table public.news_normalized_items enable row level security;
alter table public.news_review_actions enable row level security;
alter table public.intelligence_events enable row level security;

create policy "news_source_registry_read_public"
  on public.news_source_registry
  for select
  using (true);

create policy "news_source_collections_read_public"
  on public.news_source_collections
  for select
  using (true);

create policy "news_collection_runs_read_public"
  on public.news_collection_runs
  for select
  using (true);

create policy "news_normalized_items_read_public"
  on public.news_normalized_items
  for select
  using (true);

create policy "news_review_actions_read_public"
  on public.news_review_actions
  for select
  using (true);

create policy "intelligence_events_read_public"
  on public.intelligence_events
  for select
  using (true);

commit;

